// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.TagModule.Application.Services.TagStatistic;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagStatistic;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.Infrastructure.Web.Helpers;
using QuickCode.BirHaber.Application.Contracts;

namespace QuickCode.BirHaber.TagModule.Application.Tests.Services.TagStatistic
{
    public class InsertTagStatisticCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<ITagStatisticRepository> _repositoryMock;
        private readonly Mock<ILogger<TagStatisticService>> _loggerMock;
        private readonly TagStatisticService _service;
        public InsertTagStatisticCommandTests()
        {
            _repositoryMock = new Mock<ITagStatisticRepository>();
            _loggerMock = new Mock<ILogger<TagStatisticService>>();
            _service = new TagStatisticService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TagStatisticDto>("tr");
            var fakeResponse = new RepoResponse<TagStatisticDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<TagStatisticDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<TagStatisticDto>()), Times.Once);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TagStatisticDto>("tr");
            var fakeResponse = new RepoResponse<TagStatisticDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<TagStatisticDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}