// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.ContentModule.Domain.Entities;
using QuickCode.BirHaber.ContentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.ContentModule.Application.Dtos.ArticleStatistic;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Application.Services.ArticleStatistic
{
    public partial class ArticleStatisticService : IArticleStatisticService
    {
        private readonly ILogger<ArticleStatisticService> _logger;
        private readonly IArticleStatisticRepository _repository;
        public ArticleStatisticService(ILogger<ArticleStatisticService> logger, IArticleStatisticRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<ArticleStatisticDto>> InsertAsync(ArticleStatisticDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(ArticleStatisticDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, ArticleStatisticDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<ArticleStatisticDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<ArticleStatisticDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByArticleResponseDto>>> GetByArticleAsync(int articleStatisticArticleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByArticleAsync(articleStatisticArticleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetWeeklyStatsResponseDto>>> GetWeeklyStatsAsync(int articleStatisticArticleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetWeeklyStatsAsync(articleStatisticArticleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetTopPerformingResponseDto>> GetTopPerformingAsync()
        {
            var returnValue = await _repository.GetTopPerformingAsync();
            return returnValue.ToResponse();
        }
    }
}