// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CommentModule.Application.Dtos.Comment;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Services.Comment
{
    public partial class CommentService : ICommentService
    {
        private readonly ILogger<CommentService> _logger;
        private readonly ICommentRepository _repository;
        public CommentService(ILogger<CommentService> logger, ICommentRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<CommentDto>> InsertAsync(CommentDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(CommentDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, CommentDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<CommentDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<CommentDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByArticleResponseDto>>> GetByArticleAsync(int commentArticleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByArticleAsync(commentArticleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPendingApprovalAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetRepliesResponseDto>>> GetRepliesAsync(int commentParentCommentId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetRepliesAsync(commentParentCommentId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByReaderResponseDto>>> GetByReaderAsync(int commentReaderId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByReaderAsync(commentReaderId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetTopCommentsResponseDto>>> GetTopCommentsAsync(int commentArticleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetTopCommentsAsync(commentArticleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPinnedCommentsResponseDto>>> GetPinnedCommentsAsync(int commentArticleId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPinnedCommentsAsync(commentArticleId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetSpamCommentsResponseDto>>> GetSpamCommentsAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetSpamCommentsAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetDailyCommentsResponseDto>> GetDailyCommentsAsync()
        {
            var returnValue = await _repository.GetDailyCommentsAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetCommentStatsResponseDto>> GetCommentStatsAsync()
        {
            var returnValue = await _repository.GetCommentStatsAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetSentimentBreakdownResponseDto>> GetSentimentBreakdownAsync()
        {
            var returnValue = await _repository.GetSentimentBreakdownAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ApproveAsync(int commentId, ApproveRequestDto updateRequest)
        {
            var returnValue = await _repository.ApproveAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> RejectAsync(int commentId, RejectRequestDto updateRequest)
        {
            var returnValue = await _repository.RejectAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> MarkSpamAsync(int commentId, MarkSpamRequestDto updateRequest)
        {
            var returnValue = await _repository.MarkSpamAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> PinCommentAsync(int commentId, PinCommentRequestDto updateRequest)
        {
            var returnValue = await _repository.PinCommentAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UnpinCommentAsync(int commentId, UnpinCommentRequestDto updateRequest)
        {
            var returnValue = await _repository.UnpinCommentAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> IncrementLikesAsync(int commentId, IncrementLikesRequestDto updateRequest)
        {
            var returnValue = await _repository.IncrementLikesAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> IncrementDislikesAsync(int commentId, IncrementDislikesRequestDto updateRequest)
        {
            var returnValue = await _repository.IncrementDislikesAsync(commentId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> RemoveCommentAsync(int commentId)
        {
            var returnValue = await _repository.RemoveCommentAsync(commentId);
            return returnValue.ToResponse();
        }
    }
}