// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.ContentModule.Domain.Entities;
using QuickCode.BirHaber.ContentModule.Application.Dtos.ContentCategory;
using System.Threading.Tasks;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Application.Interfaces.Repositories
{
    public partial interface IContentCategoryRepository : IBaseRepository<ContentCategoryDto>
    {
        Task<RepoResponse<ContentCategoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByArticleResponseDto>>> GetByArticleAsync(int contentCategoryArticleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int contentCategoryCategoryId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> RemoveCategoryAsync(int contentCategoryArticleId, int contentCategoryCategoryId);
    }
}