-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT A.[ID], A.[TITLE], A.[SLUG], A.[FEATURED_IMAGE_URL], A.[AUTHOR_ID], A.[PUBLISHED_DATE], A.[VIEW_COUNT] 
FROM [ARTICLES] A 
WHERE A.[IsDeleted] = 0 
	AND A.[PRIORITY] = 'URGENT' 
	AND A.[STATUS] = 'PUBLISHED' 
ORDER BY A.[PUBLISHED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 