// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationStatistic;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Services.NotificationStatistic
{
    public partial class NotificationStatisticService : INotificationStatisticService
    {
        private readonly ILogger<NotificationStatisticService> _logger;
        private readonly INotificationStatisticRepository _repository;
        public NotificationStatisticService(ILogger<NotificationStatisticService> logger, INotificationStatisticRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<NotificationStatisticDto>> InsertAsync(NotificationStatisticDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(NotificationStatisticDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, NotificationStatisticDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<NotificationStatisticDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<NotificationStatisticDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(NotificationType notificationStatisticNotificationType, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByTypeAsync(notificationStatisticNotificationType, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetDailyStatsResponseDto>> GetDailyStatsAsync()
        {
            var returnValue = await _repository.GetDailyStatsAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetChannelPerformanceResponseDto>> GetChannelPerformanceAsync()
        {
            var returnValue = await _repository.GetChannelPerformanceAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetDeliveryRateResponseDto>> GetDeliveryRateAsync()
        {
            var returnValue = await _repository.GetDeliveryRateAsync();
            return returnValue.ToResponse();
        }
    }
}