// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.ContentModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Editor
    {
        public static class Query
        {
            private const string _prefix = "ContentModule.Editor.Query";
            private const string _sqlScriptStem = "Editor";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string GetByDepartment => ResourceKey($"{_sqlScriptStem}.GetByDepartment.g.sql");
        }
    }
}