-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT WH.[ID], WH.[TEMPERATURE], WH.[CONDITION], WH.[HUMIDITY], WH.[WIND_SPEED], WH.[RECORDED_DATE] 
FROM [WEATHER_HISTORIES] WH 
WHERE WH.[IsDeleted] = 0 
	AND WH.[CITY_ID] = @PRM_WEATHER_HISTORY_CITY_ID 
ORDER BY WH.[RECORDED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 