// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentLike;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Services.CommentLike
{
    public partial class CommentLikeService : ICommentLikeService
    {
        private readonly ILogger<CommentLikeService> _logger;
        private readonly ICommentLikeRepository _repository;
        public CommentLikeService(ILogger<CommentLikeService> logger, ICommentLikeRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<CommentLikeDto>> InsertAsync(CommentLikeDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(CommentLikeDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, CommentLikeDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<CommentLikeDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<CommentLikeDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByCommentResponseDto>>> GetByCommentAsync(int commentLikeCommentId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByCommentAsync(commentLikeCommentId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByReaderResponseDto>>> GetByReaderAsync(int commentLikeReaderId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByReaderAsync(commentLikeReaderId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetLikeCountResponseDto>> GetLikeCountAsync(int commentLikeCommentId, string commentLikeLikeType)
        {
            var returnValue = await _repository.GetLikeCountAsync(commentLikeCommentId, commentLikeLikeType);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> RemoveLikeAsync(int commentLikeCommentId, int commentLikeReaderId)
        {
            var returnValue = await _repository.RemoveLikeAsync(commentLikeCommentId, commentLikeReaderId);
            return returnValue.ToResponse();
        }
    }
}