IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_STATISTICS', N'U') AND name = N'IX_CATEGORY_STATISTICS_IsDeleted')
BEGIN
    CREATE INDEX [IX_CATEGORY_STATISTICS_IsDeleted] ON [dbo].[CATEGORY_STATISTICS] ([IsDeleted]);
END