IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FEATURED_CATEGORIES', N'U') AND name = N'IX_FEATURED_CATEGORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_FEATURED_CATEGORIES_IsDeleted] ON [dbo].[FEATURED_CATEGORIES] ([IsDeleted]);
END