IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_MODERATORS', N'U') AND name = N'IX_CATEGORY_MODERATORS_IsDeleted')
BEGIN
    CREATE INDEX [IX_CATEGORY_MODERATORS_IsDeleted] ON [dbo].[CATEGORY_MODERATORS] ([IsDeleted]);
END