IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_MODERATORS', N'U') AND name = N'IX_CATEGORY_MODERATORS_CATEGORY_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_CATEGORY_MODERATORS_CATEGORY_ID_IS_ACTIVE] ON [dbo].[CATEGORY_MODERATORS] ([CATEGORY_ID], [IS_ACTIVE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_MODERATORS', N'U') AND name = N'IX_CATEGORY_MODERATORS_CATEGORY_ID_MODERATOR_ID')
BEGIN
    CREATE INDEX [IX_CATEGORY_MODERATORS_CATEGORY_ID_MODERATOR_ID] ON [dbo].[CATEGORY_MODERATORS] ([CATEGORY_ID], [MODERATOR_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_MODERATORS', N'U') AND name = N'IX_CATEGORY_MODERATORS_MODERATOR_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_CATEGORY_MODERATORS_MODERATOR_ID_IS_ACTIVE] ON [dbo].[CATEGORY_MODERATORS] ([MODERATOR_ID], [IS_ACTIVE]);
END