IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_TEMPLATES', N'U') AND name = N'IX_CATEGORY_TEMPLATES_IsDeleted')
BEGIN
    CREATE INDEX [IX_CATEGORY_TEMPLATES_IsDeleted] ON [dbo].[CATEGORY_TEMPLATES] ([IsDeleted]);
END