IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_TEMPLATES', N'U') AND name = N'IX_CATEGORY_TEMPLATES_CATEGORY_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_CATEGORY_TEMPLATES_CATEGORY_ID_IS_ACTIVE] ON [dbo].[CATEGORY_TEMPLATES] ([CATEGORY_ID], [IS_ACTIVE]);
END