IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_FEATURED_CATEGORIES_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.FEATURED_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[FEATURED_CATEGORIES] ADD CONSTRAINT [FK_FEATURED_CATEGORIES_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END