IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_STATISTICS_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_STATISTICS] ADD CONSTRAINT [FK_CATEGORY_STATISTICS_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END