IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_STATISTICS', N'U') AND name = N'IX_CATEGORY_STATISTICS_CATEGORY_ID_STATISTICS_DATE')
BEGIN
    CREATE INDEX [IX_CATEGORY_STATISTICS_CATEGORY_ID_STATISTICS_DATE] ON [dbo].[CATEGORY_STATISTICS] ([CATEGORY_ID], [STATISTICS_DATE]);
END