IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORIES_CATEGORIES_PARENT_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORIES] ADD CONSTRAINT [FK_CATEGORIES_CATEGORIES_PARENT_CATEGORY_ID] FOREIGN KEY ([PARENT_CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_MODERATORS_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_MODERATORS'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_MODERATORS] ADD CONSTRAINT [FK_CATEGORY_MODERATORS_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_STATISTICS_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_STATISTICS] ADD CONSTRAINT [FK_CATEGORY_STATISTICS_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_TEMPLATES_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_TEMPLATES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_TEMPLATES] ADD CONSTRAINT [FK_CATEGORY_TEMPLATES_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_FEATURED_CATEGORIES_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.FEATURED_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[FEATURED_CATEGORIES] ADD CONSTRAINT [FK_FEATURED_CATEGORIES_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END