IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_TEMPLATES_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_TEMPLATES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_TEMPLATES] ADD CONSTRAINT [FK_CATEGORY_TEMPLATES_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END