IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORIES', N'U') AND name = N'IX_CATEGORIES_IS_ACTIVE_ARTICLE_COUNT')
BEGIN
    CREATE INDEX [IX_CATEGORIES_IS_ACTIVE_ARTICLE_COUNT] ON [dbo].[CATEGORIES] ([IS_ACTIVE], [ARTICLE_COUNT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORIES', N'U') AND name = N'IX_CATEGORIES_PARENT_CATEGORY_ID')
BEGIN
    CREATE INDEX [IX_CATEGORIES_PARENT_CATEGORY_ID] ON [dbo].[CATEGORIES] ([PARENT_CATEGORY_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORIES', N'U') AND name = N'IX_CATEGORIES_SLUG')
BEGIN
    CREATE INDEX [IX_CATEGORIES_SLUG] ON [dbo].[CATEGORIES] ([SLUG]);
END