IF OBJECT_ID(N'dbo.CATEGORY_STATISTICS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[CATEGORY_STATISTICS] (
        [ID] int IDENTITY(1,1) NOT NULL,
        [CATEGORY_ID] int NOT NULL,
        [DAILY_ARTICLES] int NOT NULL DEFAULT '0',
        [DAILY_VIEWS] int NOT NULL DEFAULT '0',
        [STATISTICS_DATE] datetime2(7) NOT NULL,
        [DAILY_TOTAL_VIEWS] nvarchar(50) NOT NULL,
        [IsDeleted] bit NOT NULL DEFAULT 0,
        [DeletedOnUtc] datetime2(7) NULL,
        CONSTRAINT [PK_CATEGORY_STATISTICS] PRIMARY KEY ([ID])
    );
END;