// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.TagModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;

namespace QuickCode.BirHaber.TagModule.Domain.Entities;

[Table("TAG_SEARCH_HISTORIES")]
public partial class TagSearchHistory : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("TAG_ID")]
	public int TagId { get; set; }
	
	[Column("SEARCH_QUERY")]
	[StringLength(250)]
	public string SearchQuery { get; set; }
	
	[Column("SEARCH_COUNT")]
	public int SearchCount { get; set; }
	
	[Column("LAST_SEARCHED_DATE")]
	public DateTime LastSearchedDate { get; set; }
	
	[ForeignKey("TagId")]
	[InverseProperty(nameof(Tag.TagSearchHistories))]
	public virtual Tag Tag { get; set; } = null!;
}

