// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CategoryModule.Domain.Entities;
using QuickCode.BirHaber.CategoryModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.CategoryTemplate;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Services.CategoryTemplate
{
    public partial class CategoryTemplateService : ICategoryTemplateService
    {
        private readonly ILogger<CategoryTemplateService> _logger;
        private readonly ICategoryTemplateRepository _repository;
        public CategoryTemplateService(ILogger<CategoryTemplateService> logger, ICategoryTemplateRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<CategoryTemplateDto>> InsertAsync(CategoryTemplateDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(CategoryTemplateDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, CategoryTemplateDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<CategoryTemplateDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<CategoryTemplateDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int categoryTemplateCategoryId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByCategoryAsync(categoryTemplateCategoryId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveTemplatesResponseDto>>> GetActiveTemplatesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveTemplatesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> DeactivateAsync(int categoryTemplateId, DeactivateRequestDto updateRequest)
        {
            var returnValue = await _repository.DeactivateAsync(categoryTemplateId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}