-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CR.[ID], CR.[COMMENT_ID], CR.[REPORTER_ID], CR.[REPORT_REASON], CR.[CREATED_DATE] 
FROM [COMMENT_REPORTS] CR 
WHERE CR.[IsDeleted] = 0 
	AND CR.[STATUS] = 'PENDING' 
ORDER BY CR.[CREATED_DATE] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 