// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.CommentModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class CommentModerationQueue
    {
        public static class Command
        {
            private const string _prefix = "CommentModule.CommentModerationQueue.Command";
            private const string _sqlScriptStem = "CommentModerationQueue";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string AssignModerator => ResourceKey($"{_sqlScriptStem}.AssignModerator.g.sql");
            public static string CompleteReview => ResourceKey($"{_sqlScriptStem}.CompleteReview.g.sql");
        }
    }
}