-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [COMMENT_MODERATION_QUEUES] 
	SET [ASSIGNED_MODERATOR_ID] = @COMMENT_MODERATION_QUEUE_ASSIGNED_MODERATOR_ID 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_COMMENT_MODERATION_QUEUE_ID