-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TS.[ID], TS.[SYNONYM_TAG_ID] 
FROM [TAG_SYNONYMS] TS 
WHERE TS.[IsDeleted] = 0 
	AND TS.[PRIMARY_TAG_ID] = @PRM_TAG_SYNONYM_PRIMARY_TAG_ID 
	AND TS.[IS_ACTIVE] = 1 
ORDER BY TS.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 