// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CategoryModule.Domain.Entities;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.Category;
using System.Threading.Tasks;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Interfaces.Repositories
{
    public partial interface ICategoryRepository : IBaseRepository<CategoryDto>
    {
        Task<RepoResponse<CategoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetParentCategoriesResponseDto>>> GetParentCategoriesAsync(int categoryParentCategoryId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetSubcategoriesResponseDto>>> GetSubcategoriesAsync(int categoryParentCategoryId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetBySlugResponseDto>> GetBySlugAsync(string categorySlug);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string categoryName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetTopCategoriesResponseDto>>> GetTopCategoriesAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetCategoryStatsResponseDto>> GetCategoryStatsAsync();
        Task<RepoResponse<int>> UpdateArticleCountAsync(int categoryId, UpdateArticleCountRequestDto updateRequest);
        Task<RepoResponse<int>> DeactivateAsync(int categoryId, DeactivateRequestDto updateRequest);
        Task<RepoResponse<int>> ReorderAsync(int categoryId, ReorderRequestDto updateRequest);
        Task<RepoResponse<int>> ArchiveUnusedAsync(CategoryStatus categoryStatus);
    }
}