// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.CategoryTemplate;
using CategoryTemplateEntity = QuickCode.BirHaber.CategoryModule.Domain.Entities.CategoryTemplate;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Mappings
{
    public static class CategoryTemplateMappings
    {
        public static List<CategoryTemplateDto> ToDto(this IEnumerable<CategoryTemplateEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CategoryTemplateDto ToDto(this CategoryTemplateEntity model)
        {
            return new CategoryTemplateDto
            {
                Id = model.Id,
                CategoryId = model.CategoryId,
                TemplateName = model.TemplateName,
                TemplateConfig = model.TemplateConfig,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static CategoryTemplateEntity ToEntity(this CategoryTemplateDto model)
        {
            return new CategoryTemplateEntity
            {
                Id = model.Id,
                CategoryId = model.CategoryId,
                TemplateName = model.TemplateName,
                TemplateConfig = model.TemplateConfig,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}