// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.FeaturedCategory;
using FeaturedCategoryEntity = QuickCode.BirHaber.CategoryModule.Domain.Entities.FeaturedCategory;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Mappings
{
    public static class FeaturedCategoryMappings
    {
        public static List<FeaturedCategoryDto> ToDto(this IEnumerable<FeaturedCategoryEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static FeaturedCategoryDto ToDto(this FeaturedCategoryEntity model)
        {
            return new FeaturedCategoryDto
            {
                Id = model.Id,
                CategoryId = model.CategoryId,
                FeaturedPosition = model.FeaturedPosition,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                IsActive = model.IsActive
            };
        }

        public static FeaturedCategoryEntity ToEntity(this FeaturedCategoryDto model)
        {
            return new FeaturedCategoryEntity
            {
                Id = model.Id,
                CategoryId = model.CategoryId,
                FeaturedPosition = model.FeaturedPosition,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                IsActive = model.IsActive
            };
        }
    }
}