// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.TagModule.Application.Dtos.TagSearchHistory;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories;
internal static class TagSearchHistoryCrudSqlBindings
{
    public const string StoreTableName = "TAG_SEARCH_HISTORIES";
    public const string ParameterNamePrefix = "TAG_SEARCH_HISTORY";
    public const string IdParameterName = "PRM_TAG_SEARCH_HISTORY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetByTag = "GetByTag";
        public const string GetPopularSearches = "GetPopularSearches";
        public const string IncrementSearchCount = "IncrementSearchCount";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TAG_ID", nameof(TagSearchHistoryDto.TagId)),
        ("SEARCH_QUERY", nameof(TagSearchHistoryDto.SearchQuery)),
        ("SEARCH_COUNT", nameof(TagSearchHistoryDto.SearchCount)),
        ("LAST_SEARCHED_DATE", nameof(TagSearchHistoryDto.LastSearchedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("TAG_ID", nameof(TagSearchHistoryDto.TagId)),
        ("SEARCH_QUERY", nameof(TagSearchHistoryDto.SearchQuery)),
        ("SEARCH_COUNT", nameof(TagSearchHistoryDto.SearchCount)),
        ("LAST_SEARCHED_DATE", nameof(TagSearchHistoryDto.LastSearchedDate)),
        ("ID", nameof(TagSearchHistoryDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(TagSearchHistoryDto.Id))
    };
}