// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.Notification;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Services.Notification
{
    public partial interface INotificationService
    {
        Task<Response<NotificationDto>> InsertAsync(NotificationDto request);
        Task<Response<bool>> DeleteAsync(NotificationDto request);
        Task<Response<bool>> UpdateAsync(int id, NotificationDto request);
        Task<Response<List<NotificationDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<NotificationDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByReaderResponseDto>>> GetByReaderAsync(int notificationReaderId, int? pageNumber, int? pageSize);
        Task<Response<List<GetUnreadResponseDto>>> GetUnreadAsync(int notificationReaderId, int? pageNumber, int? pageSize);
        Task<Response<List<GetPendingResponseDto>>> GetPendingAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(int notificationReaderId, NotificationType notificationNotificationType, int? pageNumber, int? pageSize);
        Task<Response<List<GetByChannelResponseDto>>> GetByChannelAsync(NotificationChannel notificationChannel, int? pageNumber, int? pageSize);
        Task<Response<List<GetFailedNotificationsResponseDto>>> GetFailedNotificationsAsync(int? pageNumber, int? pageSize);
        Task<Response<long>> GetUnreadCountAsync(int notificationReaderId);
        Task<Response<int>> MarkAsReadAsync(int notificationId, MarkAsReadRequestDto updateRequest);
        Task<Response<int>> MarkAsSentAsync(int notificationId, MarkAsSentRequestDto updateRequest);
        Task<Response<int>> MarkAsFailedAsync(int notificationId, MarkAsFailedRequestDto updateRequest);
        Task<Response<int>> CleanupOldReadAsync(NotificationStatus notificationStatus);
    }
}