// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationStatistic;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Services.NotificationStatistic
{
    public partial interface INotificationStatisticService
    {
        Task<Response<NotificationStatisticDto>> InsertAsync(NotificationStatisticDto request);
        Task<Response<bool>> DeleteAsync(NotificationStatisticDto request);
        Task<Response<bool>> UpdateAsync(int id, NotificationStatisticDto request);
        Task<Response<List<NotificationStatisticDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<NotificationStatisticDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(NotificationType notificationStatisticNotificationType, int? pageNumber, int? pageSize);
        Task<Response<GetDailyStatsResponseDto>> GetDailyStatsAsync();
        Task<Response<GetChannelPerformanceResponseDto>> GetChannelPerformanceAsync();
        Task<Response<GetDeliveryRateResponseDto>> GetDeliveryRateAsync();
    }
}