// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationBatch;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Services.NotificationBatch
{
    public partial interface INotificationBatchService
    {
        Task<Response<NotificationBatchDto>> InsertAsync(NotificationBatchDto request);
        Task<Response<bool>> DeleteAsync(NotificationBatchDto request);
        Task<Response<bool>> UpdateAsync(int id, NotificationBatchDto request);
        Task<Response<List<NotificationBatchDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<NotificationBatchDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetPendingBatchesResponseDto>>> GetPendingBatchesAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(NotificationType notificationBatchNotificationType, int? pageNumber, int? pageSize);
        Task<Response<GetBatchProgressResponseDto>> GetBatchProgressAsync(int notificationBatchId);
        Task<Response<List<GetCompletedBatchesResponseDto>>> GetCompletedBatchesAsync(int? pageNumber, int? pageSize);
        Task<Response<int>> UpdateSentCountAsync(int notificationBatchId, UpdateSentCountRequestDto updateRequest);
        Task<Response<int>> UpdateDeliveredCountAsync(int notificationBatchId, UpdateDeliveredCountRequestDto updateRequest);
        Task<Response<int>> CompleteBatchAsync(int notificationBatchId, CompleteBatchRequestDto updateRequest);
    }
}