-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [NOTIFICATION_TYPE],
    [CHANNEL],
    [DAILY_SENT],
    [DAILY_DELIVERED],
    [DAILY_READ],
    [DAILY_FAILED],
    [STATISTICS_DATE]
FROM [dbo].[NOTIFICATION_STATISTICS]
WHERE
    [ID] = @PRM_NOTIFICATION_STATISTIC_ID
    AND [IsDeleted] = 0;