// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherAlert;
using QuickCode.BirHaber.WeatherModule.Application.Mappings;
using QuickCode.BirHaber.WeatherModule.Persistence.Sql;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Persistence.Repositories
{
    public partial class WeatherAlertRepository : BaseRepository, IWeatherAlertRepository
    {
        public async Task<RepoResponse<int>> DeactivateAlertAsync(int weatherAlertId, DeactivateAlertRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(WeatherAlertCrudSqlBindings.OperationNames.DeactivateAlert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.WeatherAlert.Command.DeactivateAlert);
                var parameters = new
                {
                    PRM_WEATHER_ALERT_ID = weatherAlertId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> ExtendAlertAsync(int weatherAlertId, ExtendAlertRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(WeatherAlertCrudSqlBindings.OperationNames.ExtendAlert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.WeatherAlert.Command.ExtendAlert);
                var parameters = new
                {
                    WEATHER_ALERT_END_TIME = updateRequest.WeatherAlertEndTime,
                    PRM_WEATHER_ALERT_ID = weatherAlertId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}