// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherAlert;
using QuickCode.BirHaber.WeatherModule.Application.Mappings;
using QuickCode.BirHaber.WeatherModule.Persistence.Sql;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Persistence.Repositories
{
    public partial class WeatherAlertRepository : BaseRepository, IWeatherAlertRepository
    {
        public async Task<RepoResponse<List<GetActiveAlertsResponseDto>>> GetActiveAlertsAsync(DateTime weatherAlertEndTime, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(WeatherAlertCrudSqlBindings.OperationNames.GetActiveAlerts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveAlertsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.WeatherAlert.Query.GetActiveAlerts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveAlertsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in WeatherAlert");
                }
            });
        }

        public async Task<RepoResponse<List<GetByCityResponseDto>>> GetByCityAsync(int weatherAlertCityId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(WeatherAlertCrudSqlBindings.OperationNames.GetByCity, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCityResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.WeatherAlert.Query.GetByCity);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_WEATHER_ALERT_CITY_ID = weatherAlertCityId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCityResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in WeatherAlert");
                }
            });
        }

        public async Task<RepoResponse<List<GetCriticalAlertsResponseDto>>> GetCriticalAlertsAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(WeatherAlertCrudSqlBindings.OperationNames.GetCriticalAlerts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetCriticalAlertsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.WeatherAlert.Query.GetCriticalAlerts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetCriticalAlertsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in WeatherAlert");
                }
            });
        }

        public async Task<RepoResponse<long>> GetAlertCountAsync()
        {
            return await ExecuteWithExceptionHandling(WeatherAlertCrudSqlBindings.OperationNames.GetAlertCount, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.WeatherAlert.Query.GetAlertCount);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result);
            });
        }
    }
}