// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.CommentModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Comment
    {
        public static class Command
        {
            private const string _prefix = "CommentModule.Comment.Command";
            private const string _sqlScriptStem = "Comment";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string Approve => ResourceKey($"{_sqlScriptStem}.Approve.g.sql");
            public static string Reject => ResourceKey($"{_sqlScriptStem}.Reject.g.sql");
            public static string MarkSpam => ResourceKey($"{_sqlScriptStem}.MarkSpam.g.sql");
            public static string PinComment => ResourceKey($"{_sqlScriptStem}.PinComment.g.sql");
            public static string UnpinComment => ResourceKey($"{_sqlScriptStem}.UnpinComment.g.sql");
            public static string IncrementLikes => ResourceKey($"{_sqlScriptStem}.IncrementLikes.g.sql");
            public static string IncrementDislikes => ResourceKey($"{_sqlScriptStem}.IncrementDislikes.g.sql");
            public static string RemoveComment => ResourceKey($"{_sqlScriptStem}.RemoveComment.g.sql");
        }
    }
}