// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagSynonym;
using QuickCode.BirHaber.TagModule.Application.Mappings;
using QuickCode.BirHaber.TagModule.Persistence.Sql;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories
{
    public partial class TagSynonymRepository : BaseRepository, ITagSynonymRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public TagSynonymRepository(ILogger<TagSynonymRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "TagSynonym")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<TagSynonymDto>> InsertAsync(TagSynonymDto value)
        {
            return await ExecuteWithExceptionHandling(TagSynonymCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagSynonym.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(TagSynonymCrudSqlBindings.ParameterNamePrefix, value, TagSynonymCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.TagSynonym>(sql, p);
                return new RepoResponse<TagSynonymDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(TagSynonymDto value)
        {
            return await ExecuteWithExceptionHandling(TagSynonymCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagSynonym.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(TagSynonymCrudSqlBindings.ParameterNamePrefix, value, TagSynonymCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(TagSynonymDto value)
        {
            return await ExecuteWithExceptionHandling(TagSynonymCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagSynonym.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(TagSynonymCrudSqlBindings.ParameterNamePrefix, value, TagSynonymCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<TagSynonymDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(TagSynonymCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagSynonym.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(TagSynonymCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.TagSynonym>(sql, p);
                return row == null ? CreateNotFoundResponse<TagSynonymDto>("Not found in TagSynonym") : new RepoResponse<TagSynonymDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<TagSynonymDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(TagSynonymCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<TagSynonymDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.TagSynonym.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.TagSynonym>(sql, p);
                return new RepoResponse<List<TagSynonymDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(TagSynonymCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagSynonym.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}