// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagSearchHistory;
using System.Threading.Tasks;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories
{
    public partial interface ITagSearchHistoryRepository : IBaseRepository<TagSearchHistoryDto>
    {
        Task<RepoResponse<TagSearchHistoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByTagResponseDto>>> GetByTagAsync(int tagSearchHistoryTagId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPopularSearchesResponseDto>>> GetPopularSearchesAsync(int tagSearchHistoryTagId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> IncrementSearchCountAsync(int tagSearchHistoryTagId, string tagSearchHistorySearchQuery, IncrementSearchCountRequestDto updateRequest);
    }
}