// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagStatistic;
using System.Threading.Tasks;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories
{
    public partial interface ITagStatisticRepository : IBaseRepository<TagStatisticDto>
    {
        Task<RepoResponse<TagStatisticDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByTagResponseDto>>> GetByTagAsync(int tagStatisticTagId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWeeklyStatsResponseDto>>> GetWeeklyStatsAsync(int tagStatisticTagId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetTrendingTagsBySearchesResponseDto>> GetTrendingTagsBySearchesAsync();
    }
}