// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.CommentModule.Application.Dtos.Comment;
using QuickCode.BirHaber.CommentModule.Application.Mappings;
using QuickCode.BirHaber.CommentModule.Persistence.Sql;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Persistence.Repositories
{
    public partial class CommentRepository : BaseRepository, ICommentRepository
    {
        public async Task<RepoResponse<List<GetByArticleResponseDto>>> GetByArticleAsync(int commentArticleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetByArticle, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByArticleResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetByArticle);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COMMENT_ARTICLE_ID = commentArticleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByArticleResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetPendingApproval, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPendingApprovalResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetPendingApproval);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPendingApprovalResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<List<GetRepliesResponseDto>>> GetRepliesAsync(int commentParentCommentId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetReplies, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetRepliesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetReplies);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COMMENT_PARENT_COMMENT_ID = commentParentCommentId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetRepliesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<List<GetByReaderResponseDto>>> GetByReaderAsync(int commentReaderId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetByReader, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByReaderResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetByReader);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COMMENT_READER_ID = commentReaderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByReaderResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<List<GetTopCommentsResponseDto>>> GetTopCommentsAsync(int commentArticleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetTopComments, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetTopCommentsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetTopComments);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COMMENT_ARTICLE_ID = commentArticleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetTopCommentsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<List<GetPinnedCommentsResponseDto>>> GetPinnedCommentsAsync(int commentArticleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetPinnedComments, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPinnedCommentsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetPinnedComments);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COMMENT_ARTICLE_ID = commentArticleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPinnedCommentsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<List<GetSpamCommentsResponseDto>>> GetSpamCommentsAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetSpamComments, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetSpamCommentsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetSpamComments);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetSpamCommentsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Comment");
                }
            });
        }

        public async Task<RepoResponse<GetDailyCommentsResponseDto>> GetDailyCommentsAsync()
        {
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetDailyComments, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetDailyComments);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetDailyCommentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Comment");
            });
        }

        public async Task<RepoResponse<GetCommentStatsResponseDto>> GetCommentStatsAsync()
        {
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetCommentStats, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetCommentStats);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetCommentStatsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Comment");
            });
        }

        public async Task<RepoResponse<GetSentimentBreakdownResponseDto>> GetSentimentBreakdownAsync()
        {
            return await ExecuteWithExceptionHandling(CommentCrudSqlBindings.OperationNames.GetSentimentBreakdown, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Comment.Query.GetSentimentBreakdown);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetSentimentBreakdownResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Comment");
            });
        }
    }
}