// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherData
{
    public record WeatherDataDto
    {
        public int Id { get; init; }
        public int CityId { get; init; }
        public decimal Temperature { get; init; }
        public decimal FeelsLike { get; init; }
        public short Humidity { get; init; }
        public int Pressure { get; init; }
        public decimal WindSpeed { get; init; }
        public string WindDirection { get; init; }
        public WeatherCondition Condition { get; init; }
        public int Visibility { get; init; }
        public short UvIndex { get; init; }
        public decimal Precipitation { get; init; }
        public short CloudCoverage { get; init; }
        public DateTime LastUpdated { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}