// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentModerationQueue;
using CommentModerationQueueEntity = QuickCode.BirHaber.CommentModule.Domain.Entities.CommentModerationQueue;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Mappings
{
    public static class CommentModerationQueueMappings
    {
        public static List<CommentModerationQueueDto> ToDto(this IEnumerable<CommentModerationQueueEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CommentModerationQueueDto ToDto(this CommentModerationQueueEntity model)
        {
            return new CommentModerationQueueDto
            {
                Id = model.Id,
                CommentId = model.CommentId,
                AssignedModeratorId = model.AssignedModeratorId,
                Priority = model.Priority,
                Status = model.Status,
                CreatedDate = model.CreatedDate,
                CompletedDate = model.CompletedDate
            };
        }

        public static CommentModerationQueueEntity ToEntity(this CommentModerationQueueDto model)
        {
            return new CommentModerationQueueEntity
            {
                Id = model.Id,
                CommentId = model.CommentId,
                AssignedModeratorId = model.AssignedModeratorId,
                Priority = model.Priority,
                Status = model.Status,
                CreatedDate = model.CreatedDate,
                CompletedDate = model.CompletedDate
            };
        }
    }
}