IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CONTENT_REVISIONS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CONTENT_REVISIONS'))
BEGIN
    ALTER TABLE [dbo].[CONTENT_REVISIONS] ADD CONSTRAINT [FK_CONTENT_REVISIONS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END