IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLES_AUTHORS_AUTHOR_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLES'))
BEGIN
    ALTER TABLE [dbo].[ARTICLES] ADD CONSTRAINT [FK_ARTICLES_AUTHORS_AUTHOR_ID] FOREIGN KEY ([AUTHOR_ID]) REFERENCES [dbo].[AUTHORS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLES_EDITORS_EDITOR_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLES'))
BEGIN
    ALTER TABLE [dbo].[ARTICLES] ADD CONSTRAINT [FK_ARTICLES_EDITORS_EDITOR_ID] FOREIGN KEY ([EDITOR_ID]) REFERENCES [dbo].[EDITORS] ([ID]);
END