IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLE_STATISTICS', N'U') AND name = N'IX_ARTICLE_STATISTICS_IsDeleted')
BEGIN
    CREATE INDEX [IX_ARTICLE_STATISTICS_IsDeleted] ON [dbo].[ARTICLE_STATISTICS] ([IsDeleted]);
END