IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLES_AUTHORS_AUTHOR_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLES'))
BEGIN
    ALTER TABLE [dbo].[ARTICLES] ADD CONSTRAINT [FK_ARTICLES_AUTHORS_AUTHOR_ID] FOREIGN KEY ([AUTHOR_ID]) REFERENCES [dbo].[AUTHORS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLES_EDITORS_EDITOR_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLES'))
BEGIN
    ALTER TABLE [dbo].[ARTICLES] ADD CONSTRAINT [FK_ARTICLES_EDITORS_EDITOR_ID] FOREIGN KEY ([EDITOR_ID]) REFERENCES [dbo].[EDITORS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLE_STATISTICS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLE_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[ARTICLE_STATISTICS] ADD CONSTRAINT [FK_ARTICLE_STATISTICS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CONTENT_CATEGORIES_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CONTENT_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[CONTENT_CATEGORIES] ADD CONSTRAINT [FK_CONTENT_CATEGORIES_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CONTENT_REVISIONS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.CONTENT_REVISIONS'))
BEGIN
    ALTER TABLE [dbo].[CONTENT_REVISIONS] ADD CONSTRAINT [FK_CONTENT_REVISIONS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_FEATURED_ARTICLES_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.FEATURED_ARTICLES'))
BEGIN
    ALTER TABLE [dbo].[FEATURED_ARTICLES] ADD CONSTRAINT [FK_FEATURED_ARTICLES_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END