IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CONTENT_REVISIONS', N'U') AND name = N'IX_CONTENT_REVISIONS_ARTICLE_ID_CREATED_DATE')
BEGIN
    CREATE INDEX [IX_CONTENT_REVISIONS_ARTICLE_ID_CREATED_DATE] ON [dbo].[CONTENT_REVISIONS] ([ARTICLE_ID], [CREATED_DATE]);
END