IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_FEATURED_ARTICLES_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.FEATURED_ARTICLES'))
BEGIN
    ALTER TABLE [dbo].[FEATURED_ARTICLES] ADD CONSTRAINT [FK_FEATURED_ARTICLES_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END