IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CONTENT_REVISIONS', N'U') AND name = N'IX_CONTENT_REVISIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_CONTENT_REVISIONS_IsDeleted] ON [dbo].[CONTENT_REVISIONS] ([IsDeleted]);
END