IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLE_STATISTICS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLE_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[ARTICLE_STATISTICS] ADD CONSTRAINT [FK_ARTICLE_STATISTICS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END