IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CONTENT_CATEGORIES', N'U') AND name = N'IX_CONTENT_CATEGORIES_ARTICLE_ID_CATEGORY_ID')
BEGIN
    CREATE INDEX [IX_CONTENT_CATEGORIES_ARTICLE_ID_CATEGORY_ID] ON [dbo].[CONTENT_CATEGORIES] ([ARTICLE_ID], [CATEGORY_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CONTENT_CATEGORIES', N'U') AND name = N'IX_CONTENT_CATEGORIES_CATEGORY_ID')
BEGIN
    CREATE INDEX [IX_CONTENT_CATEGORIES_CATEGORY_ID] ON [dbo].[CONTENT_CATEGORIES] ([CATEGORY_ID]);
END