IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FEATURED_ARTICLES', N'U') AND name = N'IX_FEATURED_ARTICLES_IsDeleted')
BEGIN
    CREATE INDEX [IX_FEATURED_ARTICLES_IsDeleted] ON [dbo].[FEATURED_ARTICLES] ([IsDeleted]);
END