IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLE_STATISTICS', N'U') AND name = N'IX_ARTICLE_STATISTICS_ARTICLE_ID_STATISTICS_DATE')
BEGIN
    CREATE INDEX [IX_ARTICLE_STATISTICS_ARTICLE_ID_STATISTICS_DATE] ON [dbo].[ARTICLE_STATISTICS] ([ARTICLE_ID], [STATISTICS_DATE]);
END