IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLES', N'U') AND name = N'IX_ARTICLES_AUTHOR_ID')
BEGIN
    CREATE INDEX [IX_ARTICLES_AUTHOR_ID] ON [dbo].[ARTICLES] ([AUTHOR_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLES', N'U') AND name = N'IX_ARTICLES_CONTENT_TYPE')
BEGIN
    CREATE INDEX [IX_ARTICLES_CONTENT_TYPE] ON [dbo].[ARTICLES] ([CONTENT_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLES', N'U') AND name = N'IX_ARTICLES_EDITOR_ID')
BEGIN
    CREATE INDEX [IX_ARTICLES_EDITOR_ID] ON [dbo].[ARTICLES] ([EDITOR_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLES', N'U') AND name = N'IX_ARTICLES_STATUS_CREATED_DATE')
BEGIN
    CREATE INDEX [IX_ARTICLES_STATUS_CREATED_DATE] ON [dbo].[ARTICLES] ([STATUS], [CREATED_DATE]);
END