IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CONTENT_CATEGORIES', N'U') AND name = N'IX_CONTENT_CATEGORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_CONTENT_CATEGORIES_IsDeleted] ON [dbo].[CONTENT_CATEGORIES] ([IsDeleted]);
END