IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FEATURED_ARTICLES', N'U') AND name = N'IX_FEATURED_ARTICLES_ARTICLE_ID')
BEGIN
    CREATE INDEX [IX_FEATURED_ARTICLES_ARTICLE_ID] ON [dbo].[FEATURED_ARTICLES] ([ARTICLE_ID]);
END