// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CategoryModule.Domain.Entities;
using QuickCode.BirHaber.CategoryModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.Category;
using QuickCode.BirHaber.CategoryModule.Application.Mappings;
using QuickCode.BirHaber.CategoryModule.Persistence.Sql;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Persistence.Repositories
{
    public partial class CategoryRepository : BaseRepository, ICategoryRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.GetActive, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Category.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Category");
                }
            });
        }

        public async Task<RepoResponse<List<GetParentCategoriesResponseDto>>> GetParentCategoriesAsync(int categoryParentCategoryId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.GetParentCategories, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetParentCategoriesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Category.Query.GetParentCategories);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetParentCategoriesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Category");
                }
            });
        }

        public async Task<RepoResponse<List<GetSubcategoriesResponseDto>>> GetSubcategoriesAsync(int categoryParentCategoryId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.GetSubcategories, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetSubcategoriesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Category.Query.GetSubcategories);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CATEGORY_PARENT_CATEGORY_ID = categoryParentCategoryId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetSubcategoriesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Category");
                }
            });
        }

        public async Task<RepoResponse<GetBySlugResponseDto>> GetBySlugAsync(string categorySlug)
        {
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.GetBySlug, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Category.Query.GetBySlug);
                var parameters = new
                {
                    PRM_CATEGORY_SLUG = categorySlug
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetBySlugResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Category");
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string categoryName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.SearchByName, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Category.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CATEGORY_NAME = categoryName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Category");
                }
            });
        }

        public async Task<RepoResponse<List<GetTopCategoriesResponseDto>>> GetTopCategoriesAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.GetTopCategories, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetTopCategoriesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Category.Query.GetTopCategories);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetTopCategoriesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Category");
                }
            });
        }

        public async Task<RepoResponse<GetCategoryStatsResponseDto>> GetCategoryStatsAsync()
        {
            return await ExecuteWithExceptionHandling(CategoryCrudSqlBindings.OperationNames.GetCategoryStats, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Category.Query.GetCategoryStats);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetCategoryStatsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Category");
            });
        }
    }
}