// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.CategoryModule.Application.Dtos.Category;

namespace QuickCode.BirHaber.CategoryModule.Persistence.Repositories;
internal static class CategoryCrudSqlBindings
{
    public const string StoreTableName = "CATEGORIES";
    public const string ParameterNamePrefix = "CATEGORY";
    public const string IdParameterName = "PRM_CATEGORY_ID";
    public static class OperationNames
    {
        public const string ArchiveUnused = "ArchiveUnused";
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByPk = "GetByPk";
        public const string GetBySlug = "GetBySlug";
        public const string GetCategoryStats = "GetCategoryStats";
        public const string GetParentCategories = "GetParentCategories";
        public const string GetSubcategories = "GetSubcategories";
        public const string GetTopCategories = "GetTopCategories";
        public const string Insert = "Insert";
        public const string Reorder = "Reorder";
        public const string SearchByName = "SearchByName";
        public const string Select = "Select";
        public const string Update = "Update";
        public const string UpdateArticleCount = "UpdateArticleCount";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("NAME", nameof(CategoryDto.Name)),
        ("SLUG", nameof(CategoryDto.Slug)),
        ("DESCRIPTION", nameof(CategoryDto.Description)),
        ("PARENT_CATEGORY_ID", nameof(CategoryDto.ParentCategoryId)),
        ("ICON_URL", nameof(CategoryDto.IconUrl)),
        ("DISPLAY_ORDER", nameof(CategoryDto.DisplayOrder)),
        ("STATUS", nameof(CategoryDto.Status)),
        ("ARTICLE_COUNT", nameof(CategoryDto.ArticleCount)),
        ("IS_ACTIVE", nameof(CategoryDto.IsActive)),
        ("CREATED_DATE", nameof(CategoryDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("NAME", nameof(CategoryDto.Name)),
        ("SLUG", nameof(CategoryDto.Slug)),
        ("DESCRIPTION", nameof(CategoryDto.Description)),
        ("PARENT_CATEGORY_ID", nameof(CategoryDto.ParentCategoryId)),
        ("ICON_URL", nameof(CategoryDto.IconUrl)),
        ("DISPLAY_ORDER", nameof(CategoryDto.DisplayOrder)),
        ("STATUS", nameof(CategoryDto.Status)),
        ("ARTICLE_COUNT", nameof(CategoryDto.ArticleCount)),
        ("IS_ACTIVE", nameof(CategoryDto.IsActive)),
        ("CREATED_DATE", nameof(CategoryDto.CreatedDate)),
        ("ID", nameof(CategoryDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CategoryDto.Id))
    };
}