-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [WEATHER_ALERTS] 
	SET [END_TIME] = @WEATHER_ALERT_END_TIME 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_WEATHER_ALERT_ID