// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherPreference;

namespace QuickCode.BirHaber.WeatherModule.Persistence.Repositories;
internal static class WeatherPreferenceCrudSqlBindings
{
    public const string StoreTableName = "WEATHER_PREFERENCES";
    public const string ParameterNamePrefix = "WEATHER_PREFERENCE";
    public const string IdParameterName = "PRM_WEATHER_PREFERENCE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetAlertEnabled = "GetAlertEnabled";
        public const string GetByPk = "GetByPk";
        public const string GetByReader = "GetByReader";
        public const string Insert = "Insert";
        public const string RemovePreference = "RemovePreference";
        public const string Select = "Select";
        public const string ToggleAlerts = "ToggleAlerts";
        public const string ToggleNotifications = "ToggleNotifications";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("READER_ID", nameof(WeatherPreferenceDto.ReaderId)),
        ("CITY_ID", nameof(WeatherPreferenceDto.CityId)),
        ("ALERT_ENABLED", nameof(WeatherPreferenceDto.AlertEnabled)),
        ("NOTIFICATION_ENABLED", nameof(WeatherPreferenceDto.NotificationEnabled)),
        ("CREATED_DATE", nameof(WeatherPreferenceDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("READER_ID", nameof(WeatherPreferenceDto.ReaderId)),
        ("CITY_ID", nameof(WeatherPreferenceDto.CityId)),
        ("ALERT_ENABLED", nameof(WeatherPreferenceDto.AlertEnabled)),
        ("NOTIFICATION_ENABLED", nameof(WeatherPreferenceDto.NotificationEnabled)),
        ("CREATED_DATE", nameof(WeatherPreferenceDto.CreatedDate)),
        ("ID", nameof(WeatherPreferenceDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(WeatherPreferenceDto.Id))
    };
}