// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Web.Controllers;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationPreference;
using QuickCode.BirHaber.NotificationModule.Application.Services.NotificationPreference;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Api.Controllers
{
    public partial class NotificationPreferencesController : QuickCodeBaseApiController
    {
        private readonly INotificationPreferenceService service;
        private readonly ILogger<NotificationPreferencesController> logger;
        private readonly IServiceProvider serviceProvider;
        public NotificationPreferencesController(INotificationPreferenceService service, IServiceProvider serviceProvider, ILogger<NotificationPreferencesController> logger)
        {
            this.service = service;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<NotificationPreferenceDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await service.ListAsync(page, size);
            if (HandleResponseError(response, logger, "NotificationPreference", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await service.TotalItemCountAsync();
            if (HandleResponseError(response, logger, "NotificationPreference") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(NotificationPreferenceDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await service.GetItemAsync(id);
            if (HandleResponseError(response, logger, "NotificationPreference", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(NotificationPreferenceDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(NotificationPreferenceDto model)
        {
            var response = await service.InsertAsync(model);
            if (HandleResponseError(response, logger, "NotificationPreference") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, NotificationPreferenceDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await service.UpdateAsync(id, model);
            if (HandleResponseError(response, logger, "NotificationPreference", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await service.DeleteItemAsync(id);
            if (HandleResponseError(response, logger, "NotificationPreference", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-reader/{notificationPreferenceReaderId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByReaderResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByReaderAsync(int notificationPreferenceReaderId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByReaderAsync(notificationPreferenceReaderId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "NotificationPreference", $"NotificationPreferenceReaderId: '{notificationPreferenceReaderId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-enabled-preferences/{notificationPreferenceReaderId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetEnabledPreferencesResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetEnabledPreferencesAsync(int notificationPreferenceReaderId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetEnabledPreferencesAsync(notificationPreferenceReaderId, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "NotificationPreference", $"NotificationPreferenceReaderId: '{notificationPreferenceReaderId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-type/{notificationPreferenceReaderId:int}/{notificationPreferenceNotificationType}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByTypeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByTypeAsync(int notificationPreferenceReaderId, NotificationType notificationPreferenceNotificationType, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await service.GetByTypeAsync(notificationPreferenceReaderId, notificationPreferenceNotificationType, pageNumber, pageSize);
            if (HandleResponseError(response, logger, "NotificationPreference", $"NotificationPreferenceReaderId: '{notificationPreferenceReaderId}', NotificationPreferenceNotificationType: '{notificationPreferenceNotificationType}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("toggle-notification/{notificationPreferenceId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ToggleNotificationAsync(int notificationPreferenceId, [FromBody] ToggleNotificationRequestDto updateRequest)
        {
            var response = await service.ToggleNotificationAsync(notificationPreferenceId, updateRequest);
            if (HandleResponseError(response, logger, "NotificationPreference", $"NotificationPreferenceId: '{notificationPreferenceId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("set-frequency/{notificationPreferenceId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> SetFrequencyAsync(int notificationPreferenceId, [FromBody] SetFrequencyRequestDto updateRequest)
        {
            var response = await service.SetFrequencyAsync(notificationPreferenceId, updateRequest);
            if (HandleResponseError(response, logger, "NotificationPreference", $"NotificationPreferenceId: '{notificationPreferenceId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("remove-preference/{notificationPreferenceReaderId:int}/{notificationPreferenceNotificationType}/{notificationPreferenceChannel}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> RemovePreferenceAsync(int notificationPreferenceReaderId, NotificationType notificationPreferenceNotificationType, NotificationChannel notificationPreferenceChannel)
        {
            var response = await service.RemovePreferenceAsync(notificationPreferenceReaderId, notificationPreferenceNotificationType, notificationPreferenceChannel);
            if (HandleResponseError(response, logger, "NotificationPreference", $"NotificationPreferenceReaderId: '{notificationPreferenceReaderId}', NotificationPreferenceNotificationType: '{notificationPreferenceNotificationType}', NotificationPreferenceChannel: '{notificationPreferenceChannel}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}