// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.ContentModule.Application.Dtos.ContentRevision;
using ContentRevisionEntity = QuickCode.BirHaber.ContentModule.Domain.Entities.ContentRevision;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Application.Mappings
{
    public static class ContentRevisionMappings
    {
        public static List<ContentRevisionDto> ToDto(this IEnumerable<ContentRevisionEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ContentRevisionDto ToDto(this ContentRevisionEntity model)
        {
            return new ContentRevisionDto
            {
                Id = model.Id,
                ArticleId = model.ArticleId,
                RevisionNumber = model.RevisionNumber,
                Title = model.Title,
                Content = model.Content,
                ChangedById = model.ChangedById,
                ChangeReason = model.ChangeReason,
                CreatedDate = model.CreatedDate
            };
        }

        public static ContentRevisionEntity ToEntity(this ContentRevisionDto model)
        {
            return new ContentRevisionEntity
            {
                Id = model.Id,
                ArticleId = model.ArticleId,
                RevisionNumber = model.RevisionNumber,
                Title = model.Title,
                Content = model.Content,
                ChangedById = model.ChangedById,
                ChangeReason = model.ChangeReason,
                CreatedDate = model.CreatedDate
            };
        }
    }
}