// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.CommentModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Comment
    {
        public static class Query
        {
            private const string _prefix = "CommentModule.Comment.Query";
            private const string _sqlScriptStem = "Comment";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByArticle => ResourceKey($"{_sqlScriptStem}.GetByArticle.g.sql");
            public static string GetPendingApproval => ResourceKey($"{_sqlScriptStem}.GetPendingApproval.g.sql");
            public static string GetReplies => ResourceKey($"{_sqlScriptStem}.GetReplies.g.sql");
            public static string GetByReader => ResourceKey($"{_sqlScriptStem}.GetByReader.g.sql");
            public static string GetTopComments => ResourceKey($"{_sqlScriptStem}.GetTopComments.g.sql");
            public static string GetPinnedComments => ResourceKey($"{_sqlScriptStem}.GetPinnedComments.g.sql");
            public static string GetSpamComments => ResourceKey($"{_sqlScriptStem}.GetSpamComments.g.sql");
            public static string GetDailyComments => ResourceKey($"{_sqlScriptStem}.GetDailyComments.g.sql");
            public static string GetCommentStats => ResourceKey($"{_sqlScriptStem}.GetCommentStats.g.sql");
            public static string GetSentimentBreakdown => ResourceKey($"{_sqlScriptStem}.GetSentimentBreakdown.g.sql");
        }
    }
}