-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT C.[ID], C.[READER_ID], C.[CONTENT], C.[LIKE_COUNT], C.[CREATED_DATE] 
FROM [COMMENTS] C 
WHERE C.[IsDeleted] = 0 
	AND C.[PARENT_COMMENT_ID] = @PRM_COMMENT_PARENT_COMMENT_ID 
	AND C.[STATUS] = 'APPROVED' 
ORDER BY C.[CREATED_DATE] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 