// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.NotificationModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Notification
    {
        public static class Command
        {
            private const string _prefix = "NotificationModule.Notification.Command";
            private const string _sqlScriptStem = "Notification";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string MarkAsRead => ResourceKey($"{_sqlScriptStem}.MarkAsRead.g.sql");
            public static string MarkAsSent => ResourceKey($"{_sqlScriptStem}.MarkAsSent.g.sql");
            public static string MarkAsFailed => ResourceKey($"{_sqlScriptStem}.MarkAsFailed.g.sql");
            public static string CleanupOldRead => ResourceKey($"{_sqlScriptStem}.CleanupOldRead.g.sql");
        }
    }
}