-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [NOTIFICATIONS] 
WHERE [IsDeleted] = 0 
	AND [STATUS] = 'READ' 
	AND [READ_DATE] < DATEADD(DAY, -90,
	GETDATE())