-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[ARTICLES]
SET
    [TITLE] = @PRM_ARTICLE_TITLE,
    [SLUG] = @PRM_ARTICLE_SLUG,
    [DESCRIPTION] = @PRM_ARTICLE_DESCRIPTION,
    [CONTENT] = @PRM_ARTICLE_CONTENT,
    [IS_ACTIVE] = @PRM_ARTICLE_IS_ACTIVE,
    [CREATED_DATE] = @PRM_ARTICLE_CREATED_DATE
WHERE
    [ID] = @PRM_ARTICLE_ID
    AND [IsDeleted] = 0;