// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherHistory;
using System.Threading.Tasks;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories
{
    public partial interface IWeatherHistoryRepository : IBaseRepository<WeatherHistoryDto>
    {
        Task<RepoResponse<WeatherHistoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByCityResponseDto>>> GetByCityAsync(int weatherHistoryCityId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetMonthlyHistoryResponseDto>>> GetMonthlyHistoryAsync(int weatherHistoryCityId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetTemperatureTrendResponseDto>>> GetTemperatureTrendAsync(int weatherHistoryCityId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetAverageMonthlyResponseDto>> GetAverageMonthlyAsync(int weatherHistoryCityId);
    }
}