// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherForecast;
using System.Threading.Tasks;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories
{
    public partial interface IWeatherForecastRepository : IBaseRepository<WeatherForecastDto>
    {
        Task<RepoResponse<WeatherForecastDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByCityResponseDto>>> GetByCityAsync(int weatherForecastCityId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWeeklyForecastResponseDto>>> GetWeeklyForecastAsync(int weatherForecastCityId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRainyForecastResponseDto>>> GetRainyForecastAsync(int weatherForecastCityId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetForecastCountAsync(int weatherForecastCityId);
        Task<RepoResponse<int>> UpdateForecastAsync(int weatherForecastId, UpdateForecastRequestDto updateRequest);
    }
}