// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentStatistic;
using System.Threading.Tasks;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories
{
    public partial interface ICommentStatisticRepository : IBaseRepository<CommentStatisticDto>
    {
        Task<RepoResponse<CommentStatisticDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByArticleResponseDto>>> GetByArticleAsync(int commentStatisticArticleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWeeklyStatsResponseDto>>> GetWeeklyStatsAsync(int commentStatisticArticleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetModerationLoadResponseDto>> GetModerationLoadAsync();
    }
}