// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentReport;
using System.Threading.Tasks;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories
{
    public partial interface ICommentReportRepository : IBaseRepository<CommentReportDto>
    {
        Task<RepoResponse<CommentReportDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetPendingReportsResponseDto>>> GetPendingReportsAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCommentResponseDto>>> GetByCommentAsync(int commentReportCommentId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByReporterResponseDto>>> GetByReporterAsync(int commentReportReporterId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetReportStatsResponseDto>> GetReportStatsAsync();
        Task<RepoResponse<int>> ApproveReportAsync(int commentReportId, ApproveReportRequestDto updateRequest);
        Task<RepoResponse<int>> RejectReportAsync(int commentReportId, RejectReportRequestDto updateRequest);
    }
}