// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Dtos.Comment;
using System.Threading.Tasks;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories
{
    public partial interface ICommentRepository : IBaseRepository<CommentDto>
    {
        Task<RepoResponse<CommentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByArticleResponseDto>>> GetByArticleAsync(int commentArticleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRepliesResponseDto>>> GetRepliesAsync(int commentParentCommentId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByReaderResponseDto>>> GetByReaderAsync(int commentReaderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetTopCommentsResponseDto>>> GetTopCommentsAsync(int commentArticleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPinnedCommentsResponseDto>>> GetPinnedCommentsAsync(int commentArticleId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetSpamCommentsResponseDto>>> GetSpamCommentsAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetDailyCommentsResponseDto>> GetDailyCommentsAsync();
        Task<RepoResponse<GetCommentStatsResponseDto>> GetCommentStatsAsync();
        Task<RepoResponse<GetSentimentBreakdownResponseDto>> GetSentimentBreakdownAsync();
        Task<RepoResponse<int>> ApproveAsync(int commentId, ApproveRequestDto updateRequest);
        Task<RepoResponse<int>> RejectAsync(int commentId, RejectRequestDto updateRequest);
        Task<RepoResponse<int>> MarkSpamAsync(int commentId, MarkSpamRequestDto updateRequest);
        Task<RepoResponse<int>> PinCommentAsync(int commentId, PinCommentRequestDto updateRequest);
        Task<RepoResponse<int>> UnpinCommentAsync(int commentId, UnpinCommentRequestDto updateRequest);
        Task<RepoResponse<int>> IncrementLikesAsync(int commentId, IncrementLikesRequestDto updateRequest);
        Task<RepoResponse<int>> IncrementDislikesAsync(int commentId, IncrementDislikesRequestDto updateRequest);
        Task<RepoResponse<int>> RemoveCommentAsync(int commentId);
    }
}