-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[CATEGORIES] (
    [NAME],
    [SLUG],
    [DESCRIPTION],
    [PARENT_CATEGORY_ID],
    [ICON_URL],
    [DISPLAY_ORDER],
    [STATUS],
    [ARTICLE_COUNT],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CATEGORY_NAME,
    @PRM_CATEGORY_SLUG,
    @PRM_CATEGORY_DESCRIPTION,
    @PRM_CATEGORY_PARENT_CATEGORY_ID,
    @PRM_CATEGORY_ICON_URL,
    @PRM_CATEGORY_DISPLAY_ORDER,
    @PRM_CATEGORY_STATUS,
    @PRM_CATEGORY_ARTICLE_COUNT,
    @PRM_CATEGORY_IS_ACTIVE,
    @PRM_CATEGORY_CREATED_DATE
    );