// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.Notification;
using QuickCode.BirHaber.NotificationModule.Application.Mappings;
using QuickCode.BirHaber.NotificationModule.Persistence.Sql;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Persistence.Repositories
{
    public partial class NotificationRepository : BaseRepository, INotificationRepository
    {
        public async Task<RepoResponse<int>> MarkAsReadAsync(int notificationId, MarkAsReadRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(NotificationCrudSqlBindings.OperationNames.MarkAsRead, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Notification.Command.MarkAsRead);
                var parameters = new
                {
                    PRM_NOTIFICATION_ID = notificationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkAsSentAsync(int notificationId, MarkAsSentRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(NotificationCrudSqlBindings.OperationNames.MarkAsSent, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Notification.Command.MarkAsSent);
                var parameters = new
                {
                    PRM_NOTIFICATION_ID = notificationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> MarkAsFailedAsync(int notificationId, MarkAsFailedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(NotificationCrudSqlBindings.OperationNames.MarkAsFailed, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Notification.Command.MarkAsFailed);
                var parameters = new
                {
                    PRM_NOTIFICATION_ID = notificationId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CleanupOldReadAsync(NotificationStatus notificationStatus)
        {
            return await ExecuteWithExceptionHandling(NotificationCrudSqlBindings.OperationNames.CleanupOldRead, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Notification.Command.CleanupOldRead);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}