// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentStatistic;
using QuickCode.BirHaber.CommentModule.Application.Mappings;
using QuickCode.BirHaber.CommentModule.Persistence.Sql;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Persistence.Repositories
{
    public partial class CommentStatisticRepository : BaseRepository, ICommentStatisticRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CommentStatisticRepository(ILogger<CommentStatisticRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CommentStatistic")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CommentStatisticDto>> InsertAsync(CommentStatisticDto value)
        {
            return await ExecuteWithExceptionHandling(CommentStatisticCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentStatistic.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CommentStatisticCrudSqlBindings.ParameterNamePrefix, value, CommentStatisticCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CommentStatistic>(sql, p);
                return new RepoResponse<CommentStatisticDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CommentStatisticDto value)
        {
            return await ExecuteWithExceptionHandling(CommentStatisticCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentStatistic.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CommentStatisticCrudSqlBindings.ParameterNamePrefix, value, CommentStatisticCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CommentStatisticDto value)
        {
            return await ExecuteWithExceptionHandling(CommentStatisticCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentStatistic.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CommentStatisticCrudSqlBindings.ParameterNamePrefix, value, CommentStatisticCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CommentStatisticDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CommentStatisticCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentStatistic.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CommentStatisticCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CommentStatistic>(sql, p);
                return row == null ? CreateNotFoundResponse<CommentStatisticDto>("Not found in CommentStatistic") : new RepoResponse<CommentStatisticDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CommentStatisticDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CommentStatisticCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CommentStatisticDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CommentStatistic.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CommentStatistic>(sql, p);
                return new RepoResponse<List<CommentStatisticDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CommentStatisticCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentStatistic.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}