-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [READER_ID],
    [NOTIFICATION_TYPE],
    [TITLE],
    [MESSAGE],
    [RELATED_ARTICLE_ID],
    [RELATED_COMMENT_ID],
    [STATUS],
    [CHANNEL],
    [PRIORITY],
    [READ_DATE],
    [CREATED_DATE],
    [SENT_DATE]
FROM [dbo].[NOTIFICATIONS]
WHERE
    [ID] = @PRM_NOTIFICATION_ID
    AND [IsDeleted] = 0;