// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.ContentModule.Domain.Entities;
using QuickCode.BirHaber.ContentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.ContentModule.Application.Dtos.Article;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Application.Services.Article
{
    public partial interface IArticleService
    {
        Task<Response<ArticleDto>> InsertAsync(ArticleDto request);
        Task<Response<bool>> DeleteAsync(ArticleDto request);
        Task<Response<bool>> UpdateAsync(int id, ArticleDto request);
        Task<Response<List<ArticleDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<ArticleDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetPublishedResponseDto>>> GetPublishedAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetByAuthorResponseDto>>> GetByAuthorAsync(int articleAuthorId, int? pageNumber, int? pageSize);
        Task<Response<List<GetPendingReviewResponseDto>>> GetPendingReviewAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(ContentType articleContentType, int? pageNumber, int? pageSize);
        Task<Response<List<GetFeaturedResponseDto>>> GetFeaturedAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetRecentUpdatesResponseDto>>> GetRecentUpdatesAsync(int? pageNumber, int? pageSize);
        Task<Response<List<GetTopViewedResponseDto>>> GetTopViewedAsync(int? pageNumber, int? pageSize);
        Task<Response<GetDailyPublishedResponseDto>> GetDailyPublishedAsync();
        Task<Response<List<GetByStatusResponseDto>>> GetByStatusAsync(ContentStatus articleStatus, int? pageNumber, int? pageSize);
        Task<Response<List<SearchByTitleResponseDto>>> SearchByTitleAsync(string articleTitle, int? pageNumber, int? pageSize);
        Task<Response<int>> PublishAsync(int articleId, PublishRequestDto updateRequest);
        Task<Response<int>> SendForReviewAsync(int articleId, SendForReviewRequestDto updateRequest);
        Task<Response<int>> ApproveAsync(int articleId, ApproveRequestDto updateRequest);
        Task<Response<int>> ArchiveAsync(int articleId, ArchiveRequestDto updateRequest);
        Task<Response<int>> IncrementViewsAsync(int articleId, IncrementViewsRequestDto updateRequest);
        Task<Response<int>> RemoveDraftAsync(ContentStatus articleStatus);
    }
}