// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuickCode.BirHaber.ContentModule.Domain.Enums;

public enum ContentStatus{
	[Description("Taslak durumunda")]
	Draft,
	[Description("İnceleme beklemede")]
	PendingReview,
	[Description("Onaylanmış")]
	Approved,
	[Description("Yayınlanmış")]
	Published,
	[Description("Arşivlenmiş")]
	Archived
}
