// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.IdentityModule.Domain.Entities;
using QuickCode.BirHaber.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.IdentityModule.Application.Dtos.KafkaEvent;
using QuickCode.BirHaber.IdentityModule.Application.Mappings;
using QuickCode.BirHaber.IdentityModule.Persistence.Sql;
using QuickCode.BirHaber.IdentityModule.Domain.Enums;

namespace QuickCode.BirHaber.IdentityModule.Persistence.Repositories
{
    public partial class KafkaEventRepository : BaseRepository, IKafkaEventRepository
    {
        public async Task<RepoResponse<int>> CleanKafkaEventsWithModuleNameAsync(string apiMethodDefinitionsModuleName)
        {
            return await ExecuteWithExceptionHandling(KafkaEventCrudSqlBindings.OperationNames.CleanKafkaEventsWithModuleName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Command.CleanKafkaEventsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModuleName = apiMethodDefinitionsModuleName
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CleanKafkaEventsWithModelNameAsync(string apiMethodDefinitionsModelName)
        {
            return await ExecuteWithExceptionHandling(KafkaEventCrudSqlBindings.OperationNames.CleanKafkaEventsWithModelName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Command.CleanKafkaEventsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModelName = apiMethodDefinitionsModelName
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}