// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CategoryModule.Domain.Entities;
using QuickCode.BirHaber.CategoryModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.Category;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Services.Category
{
    public partial class CategoryService : ICategoryService
    {
        private readonly ILogger<CategoryService> _logger;
        private readonly ICategoryRepository _repository;
        public CategoryService(ILogger<CategoryService> logger, ICategoryRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<CategoryDto>> InsertAsync(CategoryDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(CategoryDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, CategoryDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<CategoryDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<CategoryDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetParentCategoriesResponseDto>>> GetParentCategoriesAsync(int categoryParentCategoryId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetParentCategoriesAsync(categoryParentCategoryId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetSubcategoriesResponseDto>>> GetSubcategoriesAsync(int categoryParentCategoryId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetSubcategoriesAsync(categoryParentCategoryId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetBySlugResponseDto>> GetBySlugAsync(string categorySlug)
        {
            var returnValue = await _repository.GetBySlugAsync(categorySlug);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<SearchByNameResponseDto>>> SearchByNameAsync(string categoryName, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.SearchByNameAsync(categoryName, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetTopCategoriesResponseDto>>> GetTopCategoriesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetTopCategoriesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetCategoryStatsResponseDto>> GetCategoryStatsAsync()
        {
            var returnValue = await _repository.GetCategoryStatsAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateArticleCountAsync(int categoryId, UpdateArticleCountRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateArticleCountAsync(categoryId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> DeactivateAsync(int categoryId, DeactivateRequestDto updateRequest)
        {
            var returnValue = await _repository.DeactivateAsync(categoryId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ReorderAsync(int categoryId, ReorderRequestDto updateRequest)
        {
            var returnValue = await _repository.ReorderAsync(categoryId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ArchiveUnusedAsync(CategoryStatus categoryStatus)
        {
            var returnValue = await _repository.ArchiveUnusedAsync(categoryStatus);
            return returnValue.ToResponse();
        }
    }
}