-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [TAGS] 
	SET [USAGE_COUNT] = @TAG_USAGE_COUNT 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_TAG_ID