-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CM.[ID], CM.[MODERATOR_ID], CM.[ASSIGNED_DATE] 
FROM [CATEGORY_MODERATORS] CM 
WHERE CM.[IsDeleted] = 0 
	AND CM.[CATEGORY_ID] = @PRM_CATEGORY_MODERATOR_CATEGORY_ID 
	AND CM.[IS_ACTIVE] = 1 
ORDER BY CM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 