-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [TITLE],
    [SLUG],
    [DESCRIPTION],
    [CONTENT],
    [AUTHOR_ID],
    [EDITOR_ID],
    [CONTENT_TYPE],
    [STATUS],
    [PRIORITY],
    [FEATURED_IMAGE_URL],
    [VIEW_COUNT],
    [IS_ACTIVE],
    [CREATED_DATE],
    [PUBLISHED_DATE],
    [UPDATED_DATE]
FROM [dbo].[ARTICLES]
WHERE
    [ID] = @PRM_ARTICLE_ID
    AND [IsDeleted] = 0;