// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.ContentModule.Domain.Entities;
using QuickCode.BirHaber.ContentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.ContentModule.Application.Dtos.Editor;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Application.Services.Editor
{
    public partial class EditorService : IEditorService
    {
        private readonly ILogger<EditorService> _logger;
        private readonly IEditorRepository _repository;
        public EditorService(ILogger<EditorService> logger, IEditorRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<EditorDto>> InsertAsync(EditorDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(EditorDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, EditorDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<EditorDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<EditorDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByDepartmentResponseDto>>> GetByDepartmentAsync(string editorDepartment, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByDepartmentAsync(editorDepartment, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> DeactivateAsync(int editorId, DeactivateRequestDto updateRequest)
        {
            var returnValue = await _repository.DeactivateAsync(editorId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}