// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationPreference;
using QuickCode.BirHaber.NotificationModule.Application.Mappings;
using QuickCode.BirHaber.NotificationModule.Persistence.Sql;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Persistence.Repositories
{
    public partial class NotificationPreferenceRepository : BaseRepository, INotificationPreferenceRepository
    {
        public async Task<RepoResponse<List<GetByReaderResponseDto>>> GetByReaderAsync(int notificationPreferenceReaderId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(NotificationPreferenceCrudSqlBindings.OperationNames.GetByReader, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByReaderResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.NotificationPreference.Query.GetByReader);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_NOTIFICATION_PREFERENCE_READER_ID = notificationPreferenceReaderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByReaderResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in NotificationPreference");
                }
            });
        }

        public async Task<RepoResponse<List<GetEnabledPreferencesResponseDto>>> GetEnabledPreferencesAsync(int notificationPreferenceReaderId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(NotificationPreferenceCrudSqlBindings.OperationNames.GetEnabledPreferences, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetEnabledPreferencesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.NotificationPreference.Query.GetEnabledPreferences);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_NOTIFICATION_PREFERENCE_READER_ID = notificationPreferenceReaderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetEnabledPreferencesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in NotificationPreference");
                }
            });
        }

        public async Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(int notificationPreferenceReaderId, NotificationType notificationPreferenceNotificationType, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(NotificationPreferenceCrudSqlBindings.OperationNames.GetByType, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByTypeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.NotificationPreference.Query.GetByType);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_NOTIFICATION_PREFERENCE_READER_ID = notificationPreferenceReaderId,
                        PRM_NOTIFICATION_PREFERENCE_NOTIFICATION_TYPE = notificationPreferenceNotificationType,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByTypeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in NotificationPreference");
                }
            });
        }
    }
}