-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [CATEGORY_ID],
    [TEMPLATE_NAME],
    [TEMPLATE_CONFIG],
    [IS_ACTIVE],
    [CREATED_DATE]
FROM [dbo].[CATEGORY_TEMPLATES]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;