-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 NB.[ID], NB.[BATCH_NAME], NB.[TOTAL_RECIPIENTS], NB.[SENT_COUNT], NB.[DELIVERED_COUNT], NB.[FAILED_COUNT] 
FROM [NOTIFICATION_BATCHES] NB 
WHERE NB.[IsDeleted] = 0 
	AND NB.[ID] = @PRM_NOTIFICATION_BATCH_ID 
ORDER BY NB.[ID] 