IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_HISTORIES_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_HISTORIES] ADD CONSTRAINT [FK_WEATHER_HISTORIES_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END