IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_PREFERENCES_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_PREFERENCES'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_PREFERENCES] ADD CONSTRAINT [FK_WEATHER_PREFERENCES_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END