IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_PREFERENCES', N'U') AND name = N'IX_WEATHER_PREFERENCES_CITY_ID')
BEGIN
    CREATE INDEX [IX_WEATHER_PREFERENCES_CITY_ID] ON [dbo].[WEATHER_PREFERENCES] ([CITY_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_PREFERENCES', N'U') AND name = N'IX_WEATHER_PREFERENCES_READER_ID_ALERT_ENABLED')
BEGIN
    CREATE INDEX [IX_WEATHER_PREFERENCES_READER_ID_ALERT_ENABLED] ON [dbo].[WEATHER_PREFERENCES] ([READER_ID], [ALERT_ENABLED]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_PREFERENCES', N'U') AND name = N'IX_WEATHER_PREFERENCES_READER_ID_CITY_ID')
BEGIN
    CREATE INDEX [IX_WEATHER_PREFERENCES_READER_ID_CITY_ID] ON [dbo].[WEATHER_PREFERENCES] ([READER_ID], [CITY_ID]);
END