IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_ALERTS_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_ALERTS'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_ALERTS] ADD CONSTRAINT [FK_WEATHER_ALERTS_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END