IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_DATAS', N'U') AND name = N'IX_WEATHER_DATAS_CITY_ID_LAST_UPDATED')
BEGIN
    CREATE INDEX [IX_WEATHER_DATAS_CITY_ID_LAST_UPDATED] ON [dbo].[WEATHER_DATAS] ([CITY_ID], [LAST_UPDATED]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_DATAS', N'U') AND name = N'IX_WEATHER_DATAS_CONDITION')
BEGIN
    CREATE INDEX [IX_WEATHER_DATAS_CONDITION] ON [dbo].[WEATHER_DATAS] ([CONDITION]);
END