IF OBJECT_ID(N'dbo.WEATHER_PREFERENCES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[WEATHER_PREFERENCES] (
        [ID] int IDENTITY(1,1) NOT NULL,
        [READER_ID] int NOT NULL,
        [CITY_ID] int NOT NULL,
        [ALERT_ENABLED] bit NOT NULL DEFAULT 1,
        [NOTIFICATION_ENABLED] bit NOT NULL DEFAULT 1,
        [CREATED_DATE] datetime2(7) NOT NULL,
        [IsDeleted] bit NOT NULL DEFAULT 0,
        [DeletedOnUtc] datetime2(7) NULL,
        CONSTRAINT [PK_WEATHER_PREFERENCES] PRIMARY KEY ([ID])
    );
END;