IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_ALERTS', N'U') AND name = N'IX_WEATHER_ALERTS_CITY_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_WEATHER_ALERTS_CITY_ID_IS_ACTIVE] ON [dbo].[WEATHER_ALERTS] ([CITY_ID], [IS_ACTIVE]);
END