IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_ALERTS_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_ALERTS'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_ALERTS] ADD CONSTRAINT [FK_WEATHER_ALERTS_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_DATAS_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_DATAS'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_DATAS] ADD CONSTRAINT [FK_WEATHER_DATAS_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_FORECASTS_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_FORECASTS'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_FORECASTS] ADD CONSTRAINT [FK_WEATHER_FORECASTS_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_HISTORIES_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_HISTORIES] ADD CONSTRAINT [FK_WEATHER_HISTORIES_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_WEATHER_PREFERENCES_CITIES_CITY_ID' AND parent_object_id = OBJECT_ID(N'dbo.WEATHER_PREFERENCES'))
BEGIN
    ALTER TABLE [dbo].[WEATHER_PREFERENCES] ADD CONSTRAINT [FK_WEATHER_PREFERENCES_CITIES_CITY_ID] FOREIGN KEY ([CITY_ID]) REFERENCES [dbo].[CITIES] ([ID]);
END