IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_FORECASTS', N'U') AND name = N'IX_WEATHER_FORECASTS_CITY_ID_CONDITION_FORECAST_DATE')
BEGIN
    CREATE INDEX [IX_WEATHER_FORECASTS_CITY_ID_CONDITION_FORECAST_DATE] ON [dbo].[WEATHER_FORECASTS] ([CITY_ID], [CONDITION], [FORECAST_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_FORECASTS', N'U') AND name = N'IX_WEATHER_FORECASTS_CITY_ID_FORECAST_DATE')
BEGIN
    CREATE INDEX [IX_WEATHER_FORECASTS_CITY_ID_FORECAST_DATE] ON [dbo].[WEATHER_FORECASTS] ([CITY_ID], [FORECAST_DATE]);
END