IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_PREFERENCES', N'U') AND name = N'IX_WEATHER_PREFERENCES_IsDeleted')
BEGIN
    CREATE INDEX [IX_WEATHER_PREFERENCES_IsDeleted] ON [dbo].[WEATHER_PREFERENCES] ([IsDeleted]);
END