IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CITIES', N'U') AND name = N'IX_CITIES_COUNTRY_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_CITIES_COUNTRY_IS_ACTIVE] ON [dbo].[CITIES] ([COUNTRY], [IS_ACTIVE]);
END