IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_HISTORIES', N'U') AND name = N'IX_WEATHER_HISTORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_WEATHER_HISTORIES_IsDeleted] ON [dbo].[WEATHER_HISTORIES] ([IsDeleted]);
END