IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_FORECASTS', N'U') AND name = N'IX_WEATHER_FORECASTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_WEATHER_FORECASTS_IsDeleted] ON [dbo].[WEATHER_FORECASTS] ([IsDeleted]);
END