IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.WEATHER_HISTORIES', N'U') AND name = N'IX_WEATHER_HISTORIES_CITY_ID_RECORDED_DATE')
BEGIN
    CREATE INDEX [IX_WEATHER_HISTORIES_CITY_ID_RECORDED_DATE] ON [dbo].[WEATHER_HISTORIES] ([CITY_ID], [RECORDED_DATE]);
END