// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.IdentityModule.Domain.Entities;
using QuickCode.BirHaber.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.IdentityModule.Application.Dtos.PortalMenu;
using QuickCode.BirHaber.IdentityModule.Application.Mappings;
using QuickCode.BirHaber.IdentityModule.Persistence.Sql;
using QuickCode.BirHaber.IdentityModule.Domain.Enums;

namespace QuickCode.BirHaber.IdentityModule.Persistence.Repositories
{
    public partial class PortalMenuRepository : BaseRepository, IPortalMenuRepository
    {
        public async Task<RepoResponse<int>> DeletePortalMenuItemsWithModuleNameAsync(string portalMenuKey)
        {
            return await ExecuteWithExceptionHandling(PortalMenuCrudSqlBindings.OperationNames.DeletePortalMenuItemsWithModuleName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalMenu.Command.DeletePortalMenuItemsWithModuleName);
                var parameters = new
                {
                    PRM_PortalMenu_Key = portalMenuKey
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> DeletePortalMenuItemsWithModelNameAsync(string portalMenuKey, string portalMenuName)
        {
            return await ExecuteWithExceptionHandling(PortalMenuCrudSqlBindings.OperationNames.DeletePortalMenuItemsWithModelName, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalMenu.Command.DeletePortalMenuItemsWithModelName);
                var parameters = new
                {
                    PRM_PortalMenu_Key = portalMenuKey,
                    PRM_PortalMenu_Name = portalMenuName
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}