IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_STATISTICS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_STATISTICS] ADD CONSTRAINT [FK_COMMENT_STATISTICS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END