IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_REPORTS', N'U') AND name = N'IX_COMMENT_REPORTS_COMMENT_ID')
BEGIN
    CREATE INDEX [IX_COMMENT_REPORTS_COMMENT_ID] ON [dbo].[COMMENT_REPORTS] ([COMMENT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_REPORTS', N'U') AND name = N'IX_COMMENT_REPORTS_REPORTER_ID')
BEGIN
    CREATE INDEX [IX_COMMENT_REPORTS_REPORTER_ID] ON [dbo].[COMMENT_REPORTS] ([REPORTER_ID]);
END