IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_REPORTS', N'U') AND name = N'IX_COMMENT_REPORTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_COMMENT_REPORTS_IsDeleted] ON [dbo].[COMMENT_REPORTS] ([IsDeleted]);
END