IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENTS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENTS'))
BEGIN
    ALTER TABLE [dbo].[COMMENTS] ADD CONSTRAINT [FK_COMMENTS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENTS_COMMENTS_PARENT_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENTS'))
BEGIN
    ALTER TABLE [dbo].[COMMENTS] ADD CONSTRAINT [FK_COMMENTS_COMMENTS_PARENT_COMMENT_ID] FOREIGN KEY ([PARENT_COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_LIKES_COMMENTS_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_LIKES'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_LIKES] ADD CONSTRAINT [FK_COMMENT_LIKES_COMMENTS_COMMENT_ID] FOREIGN KEY ([COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_MODERATION_QUEUES_COMMENTS_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_MODERATION_QUEUES'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_MODERATION_QUEUES] ADD CONSTRAINT [FK_COMMENT_MODERATION_QUEUES_COMMENTS_COMMENT_ID] FOREIGN KEY ([COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_REPORTS_COMMENTS_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_REPORTS'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_REPORTS] ADD CONSTRAINT [FK_COMMENT_REPORTS_COMMENTS_COMMENT_ID] FOREIGN KEY ([COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_STATISTICS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_STATISTICS] ADD CONSTRAINT [FK_COMMENT_STATISTICS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END