IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENTS', N'U') AND name = N'IX_COMMENTS_ARTICLE_ID_IS_PINNED_STATUS')
BEGIN
    CREATE INDEX [IX_COMMENTS_ARTICLE_ID_IS_PINNED_STATUS] ON [dbo].[COMMENTS] ([ARTICLE_ID], [IS_PINNED], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENTS', N'U') AND name = N'IX_COMMENTS_ARTICLE_ID_STATUS')
BEGIN
    CREATE INDEX [IX_COMMENTS_ARTICLE_ID_STATUS] ON [dbo].[COMMENTS] ([ARTICLE_ID], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENTS', N'U') AND name = N'IX_COMMENTS_PARENT_COMMENT_ID_STATUS')
BEGIN
    CREATE INDEX [IX_COMMENTS_PARENT_COMMENT_ID_STATUS] ON [dbo].[COMMENTS] ([PARENT_COMMENT_ID], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENTS', N'U') AND name = N'IX_COMMENTS_READER_ID_STATUS')
BEGIN
    CREATE INDEX [IX_COMMENTS_READER_ID_STATUS] ON [dbo].[COMMENTS] ([READER_ID], [STATUS]);
END