IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_STATISTICS', N'U') AND name = N'IX_COMMENT_STATISTICS_IsDeleted')
BEGIN
    CREATE INDEX [IX_COMMENT_STATISTICS_IsDeleted] ON [dbo].[COMMENT_STATISTICS] ([IsDeleted]);
END