IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_LIKES_COMMENTS_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_LIKES'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_LIKES] ADD CONSTRAINT [FK_COMMENT_LIKES_COMMENTS_COMMENT_ID] FOREIGN KEY ([COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END