IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_STATISTICS', N'U') AND name = N'IX_COMMENT_STATISTICS_ARTICLE_ID_STATISTICS_DATE')
BEGIN
    CREATE INDEX [IX_COMMENT_STATISTICS_ARTICLE_ID_STATISTICS_DATE] ON [dbo].[COMMENT_STATISTICS] ([ARTICLE_ID], [STATISTICS_DATE]);
END