IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_MODERATION_QUEUES', N'U') AND name = N'IX_COMMENT_MODERATION_QUEUES_ASSIGNED_MODERATOR_ID_STATUS')
BEGIN
    CREATE INDEX [IX_COMMENT_MODERATION_QUEUES_ASSIGNED_MODERATOR_ID_STATUS] ON [dbo].[COMMENT_MODERATION_QUEUES] ([ASSIGNED_MODERATOR_ID], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_MODERATION_QUEUES', N'U') AND name = N'IX_COMMENT_MODERATION_QUEUES_COMMENT_ID')
BEGIN
    CREATE INDEX [IX_COMMENT_MODERATION_QUEUES_COMMENT_ID] ON [dbo].[COMMENT_MODERATION_QUEUES] ([COMMENT_ID]);
END