IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_MODERATION_QUEUES', N'U') AND name = N'IX_COMMENT_MODERATION_QUEUES_IsDeleted')
BEGIN
    CREATE INDEX [IX_COMMENT_MODERATION_QUEUES_IsDeleted] ON [dbo].[COMMENT_MODERATION_QUEUES] ([IsDeleted]);
END