IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENT_MODERATION_QUEUES_COMMENTS_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENT_MODERATION_QUEUES'))
BEGIN
    ALTER TABLE [dbo].[COMMENT_MODERATION_QUEUES] ADD CONSTRAINT [FK_COMMENT_MODERATION_QUEUES_COMMENTS_COMMENT_ID] FOREIGN KEY ([COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END