IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENTS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENTS'))
BEGIN
    ALTER TABLE [dbo].[COMMENTS] ADD CONSTRAINT [FK_COMMENTS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMENTS_COMMENTS_PARENT_COMMENT_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMENTS'))
BEGIN
    ALTER TABLE [dbo].[COMMENTS] ADD CONSTRAINT [FK_COMMENTS_COMMENTS_PARENT_COMMENT_ID] FOREIGN KEY ([PARENT_COMMENT_ID]) REFERENCES [dbo].[COMMENTS] ([ID]);
END