IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_LIKES', N'U') AND name = N'IX_COMMENT_LIKES_COMMENT_ID_LIKE_TYPE')
BEGIN
    CREATE INDEX [IX_COMMENT_LIKES_COMMENT_ID_LIKE_TYPE] ON [dbo].[COMMENT_LIKES] ([COMMENT_ID], [LIKE_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_LIKES', N'U') AND name = N'IX_COMMENT_LIKES_COMMENT_ID_READER_ID')
BEGIN
    CREATE INDEX [IX_COMMENT_LIKES_COMMENT_ID_READER_ID] ON [dbo].[COMMENT_LIKES] ([COMMENT_ID], [READER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMENT_LIKES', N'U') AND name = N'IX_COMMENT_LIKES_READER_ID')
BEGIN
    CREATE INDEX [IX_COMMENT_LIKES_READER_ID] ON [dbo].[COMMENT_LIKES] ([READER_ID]);
END