// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CategoryModule.Domain.Entities;
using QuickCode.BirHaber.CategoryModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.CategoryModerator;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Services.CategoryModerator
{
    public partial interface ICategoryModeratorService
    {
        Task<Response<CategoryModeratorDto>> InsertAsync(CategoryModeratorDto request);
        Task<Response<bool>> DeleteAsync(CategoryModeratorDto request);
        Task<Response<bool>> UpdateAsync(int id, CategoryModeratorDto request);
        Task<Response<List<CategoryModeratorDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<CategoryModeratorDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int categoryModeratorCategoryId, int? pageNumber, int? pageSize);
        Task<Response<List<GetByModeratorResponseDto>>> GetByModeratorAsync(int categoryModeratorModeratorId, int? pageNumber, int? pageSize);
        Task<Response<int>> DeactivateAsync(int categoryModeratorId, DeactivateRequestDto updateRequest);
        Task<Response<int>> RemoveModeratorAsync(int categoryModeratorCategoryId, int categoryModeratorModeratorId);
    }
}