-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT WA.[ID], WA.[CITY_ID], WA.[ALERT_TYPE], WA.[SEVERITY], WA.[DESCRIPTION], WA.[START_TIME] 
FROM [WEATHER_ALERTS] WA 
WHERE WA.[IsDeleted] = 0 
	AND WA.[IS_ACTIVE] = 1 
	AND WA.[END_TIME] = 'IS NULL' 
ORDER BY WA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 