// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.WeatherModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class WeatherAlert
    {
        public static class Query
        {
            private const string _prefix = "WeatherModule.WeatherAlert.Query";
            private const string _sqlScriptStem = "WeatherAlert";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActiveAlerts => ResourceKey($"{_sqlScriptStem}.GetActiveAlerts.g.sql");
            public static string GetByCity => ResourceKey($"{_sqlScriptStem}.GetByCity.g.sql");
            public static string GetCriticalAlerts => ResourceKey($"{_sqlScriptStem}.GetCriticalAlerts.g.sql");
            public static string GetAlertCount => ResourceKey($"{_sqlScriptStem}.GetAlertCount.g.sql");
        }
    }
}