// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherForecast;
using WeatherForecastEntity = QuickCode.BirHaber.WeatherModule.Domain.Entities.WeatherForecast;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Mappings
{
    public static class WeatherForecastMappings
    {
        public static List<WeatherForecastDto> ToDto(this IEnumerable<WeatherForecastEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static WeatherForecastDto ToDto(this WeatherForecastEntity model)
        {
            return new WeatherForecastDto
            {
                Id = model.Id,
                CityId = model.CityId,
                ForecastDate = model.ForecastDate,
                MinTemperature = model.MinTemperature,
                MaxTemperature = model.MaxTemperature,
                Condition = model.Condition,
                PrecipitationProbability = model.PrecipitationProbability,
                WindSpeed = model.WindSpeed,
                Humidity = model.Humidity,
                CreatedDate = model.CreatedDate
            };
        }

        public static WeatherForecastEntity ToEntity(this WeatherForecastDto model)
        {
            return new WeatherForecastEntity
            {
                Id = model.Id,
                CityId = model.CityId,
                ForecastDate = model.ForecastDate,
                MinTemperature = model.MinTemperature,
                MaxTemperature = model.MaxTemperature,
                Condition = model.Condition,
                PrecipitationProbability = model.PrecipitationProbability,
                WindSpeed = model.WindSpeed,
                Humidity = model.Humidity,
                CreatedDate = model.CreatedDate
            };
        }
    }
}