// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherData;
using WeatherDataEntity = QuickCode.BirHaber.WeatherModule.Domain.Entities.WeatherData;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Mappings
{
    public static class WeatherDataMappings
    {
        public static List<WeatherDataDto> ToDto(this IEnumerable<WeatherDataEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static WeatherDataDto ToDto(this WeatherDataEntity model)
        {
            return new WeatherDataDto
            {
                Id = model.Id,
                CityId = model.CityId,
                Temperature = model.Temperature,
                FeelsLike = model.FeelsLike,
                Humidity = model.Humidity,
                Pressure = model.Pressure,
                WindSpeed = model.WindSpeed,
                WindDirection = model.WindDirection,
                Condition = model.Condition,
                Visibility = model.Visibility,
                UvIndex = model.UvIndex,
                Precipitation = model.Precipitation,
                CloudCoverage = model.CloudCoverage,
                LastUpdated = model.LastUpdated,
                CreatedDate = model.CreatedDate
            };
        }

        public static WeatherDataEntity ToEntity(this WeatherDataDto model)
        {
            return new WeatherDataEntity
            {
                Id = model.Id,
                CityId = model.CityId,
                Temperature = model.Temperature,
                FeelsLike = model.FeelsLike,
                Humidity = model.Humidity,
                Pressure = model.Pressure,
                WindSpeed = model.WindSpeed,
                WindDirection = model.WindDirection,
                Condition = model.Condition,
                Visibility = model.Visibility,
                UvIndex = model.UvIndex,
                Precipitation = model.Precipitation,
                CloudCoverage = model.CloudCoverage,
                LastUpdated = model.LastUpdated,
                CreatedDate = model.CreatedDate
            };
        }
    }
}