// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherAlert;
using WeatherAlertEntity = QuickCode.BirHaber.WeatherModule.Domain.Entities.WeatherAlert;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Mappings
{
    public static class WeatherAlertMappings
    {
        public static List<WeatherAlertDto> ToDto(this IEnumerable<WeatherAlertEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static WeatherAlertDto ToDto(this WeatherAlertEntity model)
        {
            return new WeatherAlertDto
            {
                Id = model.Id,
                CityId = model.CityId,
                AlertType = model.AlertType,
                Severity = model.Severity,
                Description = model.Description,
                StartTime = model.StartTime,
                EndTime = model.EndTime,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static WeatherAlertEntity ToEntity(this WeatherAlertDto model)
        {
            return new WeatherAlertEntity
            {
                Id = model.Id,
                CityId = model.CityId,
                AlertType = model.AlertType,
                Severity = model.Severity,
                Description = model.Description,
                StartTime = model.StartTime,
                EndTime = model.EndTime,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}