// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.Article;
using System.Threading.Tasks;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories
{
    public partial interface IArticleRepository : IBaseRepository<ArticleDto>
    {
        Task<RepoResponse<ArticleDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
    }
}