// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationQueue;
using System.Threading.Tasks;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories
{
    public partial interface INotificationQueueRepository : IBaseRepository<NotificationQueueDto>
    {
        Task<RepoResponse<NotificationQueueDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetPendingQueueResponseDto>>> GetPendingQueueAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByChannelResponseDto>>> GetByChannelAsync(NotificationChannel notificationQueueChannel, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetFailedQueueResponseDto>>> GetFailedQueueAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetQueueSizeAsync();
        Task<RepoResponse<int>> IncrementRetryAsync(int notificationQueueId, IncrementRetryRequestDto updateRequest);
        Task<RepoResponse<int>> MarkSentAsync(int notificationQueueId, MarkSentRequestDto updateRequest);
        Task<RepoResponse<int>> CleanupProcessedAsync(NotificationStatus notificationQueueStatus);
    }
}