// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherPreference;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Services.WeatherPreference
{
    public partial class WeatherPreferenceService : IWeatherPreferenceService
    {
        private readonly ILogger<WeatherPreferenceService> _logger;
        private readonly IWeatherPreferenceRepository _repository;
        public WeatherPreferenceService(ILogger<WeatherPreferenceService> logger, IWeatherPreferenceRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<WeatherPreferenceDto>> InsertAsync(WeatherPreferenceDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(WeatherPreferenceDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, WeatherPreferenceDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<WeatherPreferenceDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<WeatherPreferenceDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByReaderResponseDto>>> GetByReaderAsync(int weatherPreferenceReaderId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByReaderAsync(weatherPreferenceReaderId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetAlertEnabledResponseDto>>> GetAlertEnabledAsync(int weatherPreferenceReaderId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetAlertEnabledAsync(weatherPreferenceReaderId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ToggleAlertsAsync(int weatherPreferenceId, ToggleAlertsRequestDto updateRequest)
        {
            var returnValue = await _repository.ToggleAlertsAsync(weatherPreferenceId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> ToggleNotificationsAsync(int weatherPreferenceId, ToggleNotificationsRequestDto updateRequest)
        {
            var returnValue = await _repository.ToggleNotificationsAsync(weatherPreferenceId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> RemovePreferenceAsync(int weatherPreferenceReaderId, int weatherPreferenceCityId)
        {
            var returnValue = await _repository.RemovePreferenceAsync(weatherPreferenceReaderId, weatherPreferenceCityId);
            return returnValue.ToResponse();
        }
    }
}