-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TOTAL_TAGS,
	SUM(T.[USAGE_COUNT]) AS TOTAL_USAGE 
FROM [TAGS] T 
WHERE T.[IsDeleted] = 0 
	AND T.[IS_ACTIVE] = 1 
	AND T.[USAGE_COUNT] > '0' 