// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.TagModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Tag
    {
        public static class Query
        {
            private const string _prefix = "TagModule.Tag.Query";
            private const string _sqlScriptStem = "Tag";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string GetBySlug => ResourceKey($"{_sqlScriptStem}.GetBySlug.g.sql");
            public static string SearchByName => ResourceKey($"{_sqlScriptStem}.SearchByName.g.sql");
            public static string GetPopularTags => ResourceKey($"{_sqlScriptStem}.GetPopularTags.g.sql");
            public static string GetTrendingTags => ResourceKey($"{_sqlScriptStem}.GetTrendingTags.g.sql");
            public static string GetTagCloud => ResourceKey($"{_sqlScriptStem}.GetTagCloud.g.sql");
        }
    }
}