// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.WeatherModule.Application.Services.WeatherForecast;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherForecast;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.Infrastructure.Web.Helpers;
using QuickCode.BirHaber.Application.Contracts;

namespace QuickCode.BirHaber.WeatherModule.Application.Tests.Services.WeatherForecast
{
    public class InsertWeatherForecastCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IWeatherForecastRepository> _repositoryMock;
        private readonly Mock<ILogger<WeatherForecastService>> _loggerMock;
        private readonly WeatherForecastService _service;
        public InsertWeatherForecastCommandTests()
        {
            _repositoryMock = new Mock<IWeatherForecastRepository>();
            _loggerMock = new Mock<ILogger<WeatherForecastService>>();
            _service = new WeatherForecastService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_Success_When_Valid_Request()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<WeatherForecastDto>("tr");
            var fakeResponse = new RepoResponse<WeatherForecastDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<WeatherForecastDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<WeatherForecastDto>()), Times.Once);
        }

        [Fact]
        public async Task InsertAsync_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<WeatherForecastDto>("tr");
            var fakeResponse = new RepoResponse<WeatherForecastDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<WeatherForecastDto>())).ReturnsAsync(fakeResponse);
            // Act
            var result = await _service.InsertAsync(fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}