// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationStatistic
{
    public record GetChannelPerformanceResponseDto
    {
        public NotificationChannel Channel { get; init; }
        public decimal WeeklySent { get; init; }
        public decimal WeeklyDelivered { get; init; }
    }
}