// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.TagModule.Application.Dtos.ArticleTag;
using ArticleTagEntity = QuickCode.BirHaber.TagModule.Domain.Entities.ArticleTag;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Mappings
{
    public static class ArticleTagMappings
    {
        public static List<ArticleTagDto> ToDto(this IEnumerable<ArticleTagEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ArticleTagDto ToDto(this ArticleTagEntity model)
        {
            return new ArticleTagDto
            {
                Id = model.Id,
                ArticleId = model.ArticleId,
                TagId = model.TagId,
                AssignedDate = model.AssignedDate
            };
        }

        public static ArticleTagEntity ToEntity(this ArticleTagDto model)
        {
            return new ArticleTagEntity
            {
                Id = model.Id,
                ArticleId = model.ArticleId,
                TagId = model.TagId,
                AssignedDate = model.AssignedDate
            };
        }
    }
}