-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CC.[ID], CC.[CATEGORY_ID], CC.[ASSIGNED_DATE] 
FROM [CONTENT_CATEGORIES] CC 
WHERE CC.[IsDeleted] = 0 
	AND CC.[ARTICLE_ID] = @PRM_CONTENT_CATEGORY_ARTICLE_ID 
ORDER BY CC.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 