-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[TAG_SEARCH_HISTORIES] (
    [TAG_ID],
    [SEARCH_QUERY],
    [SEARCH_COUNT],
    [LAST_SEARCHED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TAG_SEARCH_HISTORY_TAG_ID,
    @PRM_TAG_SEARCH_HISTORY_SEARCH_QUERY,
    @PRM_TAG_SEARCH_HISTORY_SEARCH_COUNT,
    @PRM_TAG_SEARCH_HISTORY_LAST_SEARCHED_DATE
    );