// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CategoryModule.Domain.Entities;
using QuickCode.BirHaber.CategoryModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CategoryModule.Application.Dtos.FeaturedCategory;
using QuickCode.BirHaber.CategoryModule.Domain.Enums;

namespace QuickCode.BirHaber.CategoryModule.Application.Services.FeaturedCategory
{
    public partial class FeaturedCategoryService : IFeaturedCategoryService
    {
        private readonly ILogger<FeaturedCategoryService> _logger;
        private readonly IFeaturedCategoryRepository _repository;
        public FeaturedCategoryService(ILogger<FeaturedCategoryService> logger, IFeaturedCategoryRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<FeaturedCategoryDto>> InsertAsync(FeaturedCategoryDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(FeaturedCategoryDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, FeaturedCategoryDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<FeaturedCategoryDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<FeaturedCategoryDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveFeaturedResponseDto>>> GetActiveFeaturedAsync(DateTime featuredCategoryEndDate, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveFeaturedAsync(featuredCategoryEndDate, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetExpiredResponseDto>>> GetExpiredAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetExpiredAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> DeactivateAsync(int featuredCategoryId, DeactivateRequestDto updateRequest)
        {
            var returnValue = await _repository.DeactivateAsync(featuredCategoryId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}