// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.TagModule.Application.Services.TagSearchHistory;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagSearchHistory;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.Infrastructure.Web.Helpers;
using QuickCode.BirHaber.Application.Contracts;

namespace QuickCode.BirHaber.TagModule.Application.Tests.Services.TagSearchHistory
{
    public class UpdateTagSearchHistoryCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<ITagSearchHistoryRepository> _repositoryMock;
        private readonly Mock<ILogger<TagSearchHistoryService>> _loggerMock;
        private readonly TagSearchHistoryService _service;
        public UpdateTagSearchHistoryCommandTests()
        {
            _repositoryMock = new Mock<ITagSearchHistoryRepository>();
            _loggerMock = new Mock<ILogger<TagSearchHistoryService>>();
            _service = new TagSearchHistoryService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task UpdateAsync_Should_Return_Success_When_Item_Exists()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TagSearchHistoryDto>("tr");
            var fakeGetResponse = new RepoResponse<TagSearchHistoryDto>(fakeDto, "Success");
            var fakeUpdateResponse = new RepoResponse<bool>(true, "Success");
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            _repositoryMock.Setup(r => r.UpdateAsync(It.IsAny<TagSearchHistoryDto>())).ReturnsAsync(fakeUpdateResponse);
            // Act
            var result = await _service.UpdateAsync(fakeDto.Id, fakeDto);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.True(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.UpdateAsync(It.IsAny<TagSearchHistoryDto>()), Times.Once);
        }

        [Fact]
        public async Task UpdateAsync_Should_Return_NotFound_When_Item_Does_Not_Exist()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<TagSearchHistoryDto>("tr");
            var fakeGetResponse = new RepoResponse<TagSearchHistoryDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            // Act
            var result = await _service.UpdateAsync(fakeDto.Id, fakeDto);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.False(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.UpdateAsync(It.IsAny<TagSearchHistoryDto>()), Times.Never);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}