-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [TAG_ID],
    [DAILY_ARTICLES],
    [DAILY_VIEWS],
    [DAILY_SEARCHES],
    [STATISTICS_DATE],
    [TOTAL_SEARCHES]
FROM [dbo].[TAG_STATISTICS]
WHERE
    [ID] = @PRM_TAG_STATISTIC_ID
    AND [IsDeleted] = 0;