// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.TagModule.Application.Services.ArticleTag;
using QuickCode.BirHaber.TagModule.Application.Dtos.ArticleTag;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.Infrastructure.Web.Helpers;
using QuickCode.BirHaber.Application.Contracts;

namespace QuickCode.BirHaber.TagModule.Application.Tests.Services.ArticleTag
{
    public class ArticleTagServiceDeleteTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<IArticleTagRepository> _repositoryMock;
        private readonly Mock<ILogger<ArticleTagService>> _loggerMock;
        private readonly ArticleTagService _service;
        public ArticleTagServiceDeleteTests()
        {
            _repositoryMock = new Mock<IArticleTagRepository>();
            _loggerMock = new Mock<ILogger<ArticleTagService>>();
            _service = new ArticleTagService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task DeleteItemAsync_Should_Return_Success_When_Item_Exists()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<ArticleTagDto>("tr");
            var fakeGetResponse = new RepoResponse<ArticleTagDto>(fakeDto, "Success");
            var fakeDeleteResponse = new RepoResponse<bool>(true, "Success");
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            _repositoryMock.Setup(r => r.DeleteAsync(It.IsAny<ArticleTagDto>())).ReturnsAsync(fakeDeleteResponse);
            // Act
            var result = await _service.DeleteItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.True(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.DeleteAsync(It.IsAny<ArticleTagDto>()), Times.Once);
        }

        [Fact]
        public async Task DeleteItemAsync_Should_Return_NotFound_When_Item_Does_Not_Exist()
        {
            var fakeDto = TestDataGenerator.CreateFake<ArticleTagDto>("tr");
            // Arrange
            var fakeGetResponse = new RepoResponse<ArticleTagDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            // Act
            var result = await _service.DeleteItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.False(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.DeleteAsync(It.IsAny<ArticleTagDto>()), Times.Never);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}