// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.CommentModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class CommentStatistic
    {
        public static class Query
        {
            private const string _prefix = "CommentModule.CommentStatistic.Query";
            private const string _sqlScriptStem = "CommentStatistic";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByArticle => ResourceKey($"{_sqlScriptStem}.GetByArticle.g.sql");
            public static string GetWeeklyStats => ResourceKey($"{_sqlScriptStem}.GetWeeklyStats.g.sql");
            public static string GetModerationLoad => ResourceKey($"{_sqlScriptStem}.GetModerationLoad.g.sql");
        }
    }
}