-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [FEATURED_ARTICLES] 
	SET [IS_ACTIVE] = 0, [END_DATE] = GETDATE() 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_FEATURED_ARTICLE_ID