IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLE_TAGS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLE_TAGS'))
BEGIN
    ALTER TABLE [dbo].[ARTICLE_TAGS] ADD CONSTRAINT [FK_ARTICLE_TAGS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLE_TAGS_TAGS_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLE_TAGS'))
BEGIN
    ALTER TABLE [dbo].[ARTICLE_TAGS] ADD CONSTRAINT [FK_ARTICLE_TAGS_TAGS_TAG_ID] FOREIGN KEY ([TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_SEARCH_HISTORIES_TAGS_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_SEARCH_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[TAG_SEARCH_HISTORIES] ADD CONSTRAINT [FK_TAG_SEARCH_HISTORIES_TAGS_TAG_ID] FOREIGN KEY ([TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_STATISTICS_TAGS_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[TAG_STATISTICS] ADD CONSTRAINT [FK_TAG_STATISTICS_TAGS_TAG_ID] FOREIGN KEY ([TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_SYNONYMS_TAGS_PRIMARY_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS'))
BEGIN
    ALTER TABLE [dbo].[TAG_SYNONYMS] ADD CONSTRAINT [FK_TAG_SYNONYMS_TAGS_PRIMARY_TAG_ID] FOREIGN KEY ([PRIMARY_TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_SYNONYMS_TAGS_SYNONYM_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS'))
BEGIN
    ALTER TABLE [dbo].[TAG_SYNONYMS] ADD CONSTRAINT [FK_TAG_SYNONYMS_TAGS_SYNONYM_TAG_ID] FOREIGN KEY ([SYNONYM_TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END