IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLE_TAGS_ARTICLES_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLE_TAGS'))
BEGIN
    ALTER TABLE [dbo].[ARTICLE_TAGS] ADD CONSTRAINT [FK_ARTICLE_TAGS_ARTICLES_ARTICLE_ID] FOREIGN KEY ([ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ARTICLE_TAGS_TAGS_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.ARTICLE_TAGS'))
BEGIN
    ALTER TABLE [dbo].[ARTICLE_TAGS] ADD CONSTRAINT [FK_ARTICLE_TAGS_TAGS_TAG_ID] FOREIGN KEY ([TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END