IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAG_STATISTICS', N'U') AND name = N'IX_TAG_STATISTICS_TAG_ID_STATISTICS_DATE')
BEGIN
    CREATE INDEX [IX_TAG_STATISTICS_TAG_ID_STATISTICS_DATE] ON [dbo].[TAG_STATISTICS] ([TAG_ID], [STATISTICS_DATE]);
END