IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_SEARCH_HISTORIES_TAGS_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_SEARCH_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[TAG_SEARCH_HISTORIES] ADD CONSTRAINT [FK_TAG_SEARCH_HISTORIES_TAGS_TAG_ID] FOREIGN KEY ([TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END