IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAG_SEARCH_HISTORIES', N'U') AND name = N'IX_TAG_SEARCH_HISTORIES_TAG_ID_SEARCH_QUERY')
BEGIN
    CREATE INDEX [IX_TAG_SEARCH_HISTORIES_TAG_ID_SEARCH_QUERY] ON [dbo].[TAG_SEARCH_HISTORIES] ([TAG_ID], [SEARCH_QUERY]);
END