IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLE_TAGS', N'U') AND name = N'IX_ARTICLE_TAGS_ARTICLE_ID_TAG_ID')
BEGIN
    CREATE INDEX [IX_ARTICLE_TAGS_ARTICLE_ID_TAG_ID] ON [dbo].[ARTICLE_TAGS] ([ARTICLE_ID], [TAG_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ARTICLE_TAGS', N'U') AND name = N'IX_ARTICLE_TAGS_TAG_ID')
BEGIN
    CREATE INDEX [IX_ARTICLE_TAGS_TAG_ID] ON [dbo].[ARTICLE_TAGS] ([TAG_ID]);
END