IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_STATISTICS_TAGS_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_STATISTICS'))
BEGIN
    ALTER TABLE [dbo].[TAG_STATISTICS] ADD CONSTRAINT [FK_TAG_STATISTICS_TAGS_TAG_ID] FOREIGN KEY ([TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END