IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAG_SEARCH_HISTORIES', N'U') AND name = N'IX_TAG_SEARCH_HISTORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_TAG_SEARCH_HISTORIES_IsDeleted] ON [dbo].[TAG_SEARCH_HISTORIES] ([IsDeleted]);
END