IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS', N'U') AND name = N'IX_TAG_SYNONYMS_PRIMARY_TAG_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_TAG_SYNONYMS_PRIMARY_TAG_ID_IS_ACTIVE] ON [dbo].[TAG_SYNONYMS] ([PRIMARY_TAG_ID], [IS_ACTIVE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS', N'U') AND name = N'IX_TAG_SYNONYMS_PRIMARY_TAG_ID_SYNONYM_TAG_ID')
BEGIN
    CREATE INDEX [IX_TAG_SYNONYMS_PRIMARY_TAG_ID_SYNONYM_TAG_ID] ON [dbo].[TAG_SYNONYMS] ([PRIMARY_TAG_ID], [SYNONYM_TAG_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS', N'U') AND name = N'IX_TAG_SYNONYMS_SYNONYM_TAG_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_TAG_SYNONYMS_SYNONYM_TAG_ID_IS_ACTIVE] ON [dbo].[TAG_SYNONYMS] ([SYNONYM_TAG_ID], [IS_ACTIVE]);
END