IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_SYNONYMS_TAGS_PRIMARY_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS'))
BEGIN
    ALTER TABLE [dbo].[TAG_SYNONYMS] ADD CONSTRAINT [FK_TAG_SYNONYMS_TAGS_PRIMARY_TAG_ID] FOREIGN KEY ([PRIMARY_TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_TAG_SYNONYMS_TAGS_SYNONYM_TAG_ID' AND parent_object_id = OBJECT_ID(N'dbo.TAG_SYNONYMS'))
BEGIN
    ALTER TABLE [dbo].[TAG_SYNONYMS] ADD CONSTRAINT [FK_TAG_SYNONYMS_TAGS_SYNONYM_TAG_ID] FOREIGN KEY ([SYNONYM_TAG_ID]) REFERENCES [dbo].[TAGS] ([ID]);
END