IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAGS', N'U') AND name = N'IX_TAGS_IS_ACTIVE_USAGE_COUNT')
BEGIN
    CREATE INDEX [IX_TAGS_IS_ACTIVE_USAGE_COUNT] ON [dbo].[TAGS] ([IS_ACTIVE], [USAGE_COUNT]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TAGS', N'U') AND name = N'IX_TAGS_SLUG')
BEGIN
    CREATE INDEX [IX_TAGS_SLUG] ON [dbo].[TAGS] ([SLUG]);
END