-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[TAGS] (
    [NAME],
    [SLUG],
    [DESCRIPTION],
    [STATUS],
    [USAGE_COUNT],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_TAG_NAME,
    @PRM_TAG_SLUG,
    @PRM_TAG_DESCRIPTION,
    @PRM_TAG_STATUS,
    @PRM_TAG_USAGE_COUNT,
    @PRM_TAG_IS_ACTIVE,
    @PRM_TAG_CREATED_DATE
    );