// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentLike;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Services.CommentLike
{
    public partial interface ICommentLikeService
    {
        Task<Response<CommentLikeDto>> InsertAsync(CommentLikeDto request);
        Task<Response<bool>> DeleteAsync(CommentLikeDto request);
        Task<Response<bool>> UpdateAsync(int id, CommentLikeDto request);
        Task<Response<List<CommentLikeDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<CommentLikeDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByCommentResponseDto>>> GetByCommentAsync(int commentLikeCommentId, int? pageNumber, int? pageSize);
        Task<Response<List<GetByReaderResponseDto>>> GetByReaderAsync(int commentLikeReaderId, int? pageNumber, int? pageSize);
        Task<Response<GetLikeCountResponseDto>> GetLikeCountAsync(int commentLikeCommentId, string commentLikeLikeType);
        Task<Response<int>> RemoveLikeAsync(int commentLikeCommentId, int commentLikeReaderId);
    }
}