// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentStatistic;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Services.CommentStatistic
{
    public partial interface ICommentStatisticService
    {
        Task<Response<CommentStatisticDto>> InsertAsync(CommentStatisticDto request);
        Task<Response<bool>> DeleteAsync(CommentStatisticDto request);
        Task<Response<bool>> UpdateAsync(int id, CommentStatisticDto request);
        Task<Response<List<CommentStatisticDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<CommentStatisticDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByArticleResponseDto>>> GetByArticleAsync(int commentStatisticArticleId, int? pageNumber, int? pageSize);
        Task<Response<List<GetWeeklyStatsResponseDto>>> GetWeeklyStatsAsync(int commentStatisticArticleId, int? pageNumber, int? pageSize);
        Task<Response<GetModerationLoadResponseDto>> GetModerationLoadAsync();
    }
}