// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentLike;

namespace QuickCode.BirHaber.CommentModule.Persistence.Repositories;
internal static class CommentLikeCrudSqlBindings
{
    public const string StoreTableName = "COMMENT_LIKES";
    public const string ParameterNamePrefix = "COMMENT_LIKE";
    public const string IdParameterName = "PRM_COMMENT_LIKE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByComment = "GetByComment";
        public const string GetByPk = "GetByPk";
        public const string GetByReader = "GetByReader";
        public const string GetLikeCount = "GetLikeCount";
        public const string Insert = "Insert";
        public const string RemoveLike = "RemoveLike";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("COMMENT_ID", nameof(CommentLikeDto.CommentId)),
        ("READER_ID", nameof(CommentLikeDto.ReaderId)),
        ("LIKE_TYPE", nameof(CommentLikeDto.LikeType)),
        ("CREATED_DATE", nameof(CommentLikeDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("COMMENT_ID", nameof(CommentLikeDto.CommentId)),
        ("READER_ID", nameof(CommentLikeDto.ReaderId)),
        ("LIKE_TYPE", nameof(CommentLikeDto.LikeType)),
        ("CREATED_DATE", nameof(CommentLikeDto.CreatedDate)),
        ("ID", nameof(CommentLikeDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CommentLikeDto.Id))
    };
}