// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.IdentityModule.Domain.Entities;
using QuickCode.BirHaber.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.IdentityModule.Application.Dtos.RefreshToken;
using QuickCode.BirHaber.IdentityModule.Application.Mappings;
using QuickCode.BirHaber.IdentityModule.Persistence.Sql;
using QuickCode.BirHaber.IdentityModule.Domain.Enums;

namespace QuickCode.BirHaber.IdentityModule.Persistence.Repositories
{
    public partial class RefreshTokenRepository : BaseRepository, IRefreshTokenRepository
    {
        public async Task<RepoResponse<int>> UpdateRefreshTokensAsync(string refreshTokenToken, UpdateRefreshTokensRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(RefreshTokenCrudSqlBindings.OperationNames.UpdateRefreshTokens, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Command.UpdateRefreshTokens);
                var parameters = new
                {
                    PRM_RefreshToken_Token = refreshTokenToken
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}