-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[READERS] (
    [NAME],
    [EMAIL],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_READER_NAME,
    @PRM_READER_EMAIL,
    @PRM_READER_IS_ACTIVE,
    @PRM_READER_CREATED_DATE
    );