-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[READERS]
SET
    [NAME] = @PRM_READER_NAME,
    [EMAIL] = @PRM_READER_EMAIL,
    [IS_ACTIVE] = @PRM_READER_IS_ACTIVE,
    [CREATED_DATE] = @PRM_READER_CREATED_DATE
WHERE
    [ID] = @PRM_READER_ID
    AND [IsDeleted] = 0;