// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Dtos.TagStatistic
{
    public record TagStatisticDto
    {
        public int Id { get; init; }
        public int TagId { get; init; }
        public int DailyArticles { get; init; }
        public int DailyViews { get; init; }
        public int DailySearches { get; init; }
        public DateTime StatisticsDate { get; init; }
        public string TotalSearches { get; init; }
    }
}