// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherHistory;
using QuickCode.BirHaber.WeatherModule.Application.Mappings;
using QuickCode.BirHaber.WeatherModule.Persistence.Sql;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Persistence.Repositories
{
    public partial class WeatherHistoryRepository : BaseRepository, IWeatherHistoryRepository
    {
        public async Task<RepoResponse<List<GetByCityResponseDto>>> GetByCityAsync(int weatherHistoryCityId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(WeatherHistoryCrudSqlBindings.OperationNames.GetByCity, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCityResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.WeatherHistory.Query.GetByCity);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_WEATHER_HISTORY_CITY_ID = weatherHistoryCityId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCityResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in WeatherHistory");
                }
            });
        }

        public async Task<RepoResponse<List<GetMonthlyHistoryResponseDto>>> GetMonthlyHistoryAsync(int weatherHistoryCityId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(WeatherHistoryCrudSqlBindings.OperationNames.GetMonthlyHistory, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetMonthlyHistoryResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.WeatherHistory.Query.GetMonthlyHistory);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_WEATHER_HISTORY_CITY_ID = weatherHistoryCityId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetMonthlyHistoryResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in WeatherHistory");
                }
            });
        }

        public async Task<RepoResponse<List<GetTemperatureTrendResponseDto>>> GetTemperatureTrendAsync(int weatherHistoryCityId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(WeatherHistoryCrudSqlBindings.OperationNames.GetTemperatureTrend, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetTemperatureTrendResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.WeatherHistory.Query.GetTemperatureTrend);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_WEATHER_HISTORY_CITY_ID = weatherHistoryCityId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetTemperatureTrendResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in WeatherHistory");
                }
            });
        }

        public async Task<RepoResponse<GetAverageMonthlyResponseDto>> GetAverageMonthlyAsync(int weatherHistoryCityId)
        {
            return await ExecuteWithExceptionHandling(WeatherHistoryCrudSqlBindings.OperationNames.GetAverageMonthly, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.WeatherHistory.Query.GetAverageMonthly);
                var parameters = new
                {
                    PRM_WEATHER_HISTORY_CITY_ID = weatherHistoryCityId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetAverageMonthlyResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in WeatherHistory");
            });
        }
    }
}