// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentModerationQueue;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Application.Services.CommentModerationQueue
{
    public partial class CommentModerationQueueService : ICommentModerationQueueService
    {
        private readonly ILogger<CommentModerationQueueService> _logger;
        private readonly ICommentModerationQueueRepository _repository;
        public CommentModerationQueueService(ILogger<CommentModerationQueueService> logger, ICommentModerationQueueRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<CommentModerationQueueDto>> InsertAsync(CommentModerationQueueDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(CommentModerationQueueDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, CommentModerationQueueDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<CommentModerationQueueDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<CommentModerationQueueDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPendingQueueResponseDto>>> GetPendingQueueAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPendingQueueAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByModeratorResponseDto>>> GetByModeratorAsync(int commentModerationQueueAssignedModeratorId, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByModeratorAsync(commentModerationQueueAssignedModeratorId, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetQueueSizeResponseDto>> GetQueueSizeAsync()
        {
            var returnValue = await _repository.GetQueueSizeAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> AssignModeratorAsync(int commentModerationQueueId, AssignModeratorRequestDto updateRequest)
        {
            var returnValue = await _repository.AssignModeratorAsync(commentModerationQueueId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CompleteReviewAsync(int commentModerationQueueId, CompleteReviewRequestDto updateRequest)
        {
            var returnValue = await _repository.CompleteReviewAsync(commentModerationQueueId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}