// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.WeatherModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Domain.Entities;

[Table("WEATHER_FORECASTS")]
public partial class WeatherForecast : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("CITY_ID")]
	public int CityId { get; set; }
	
	[Column("FORECAST_DATE")]
	public DateTime ForecastDate { get; set; }
	
	[Column("MIN_TEMPERATURE")]
	public decimal MinTemperature { get; set; }
	
	[Column("MAX_TEMPERATURE")]
	public decimal MaxTemperature { get; set; }
	
	[Column("CONDITION", TypeName = "nvarchar(50)")]
	public WeatherCondition Condition { get; set; }
	
	[Column("PRECIPITATION_PROBABILITY")]
	public short PrecipitationProbability { get; set; }
	
	[Column("WIND_SPEED")]
	public decimal WindSpeed { get; set; }
	
	[Column("HUMIDITY")]
	public short Humidity { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[ForeignKey("CityId")]
	[InverseProperty(nameof(City.WeatherForecasts))]
	public virtual City City { get; set; } = null!;
}

