// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.WeatherModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Domain.Entities;

[Table("WEATHER_DATAS")]
public partial class WeatherData : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("CITY_ID")]
	public int CityId { get; set; }
	
	[Column("TEMPERATURE")]
	public decimal Temperature { get; set; }
	
	[Column("FEELS_LIKE")]
	public decimal FeelsLike { get; set; }
	
	[Column("HUMIDITY")]
	public short Humidity { get; set; }
	
	[Column("PRESSURE")]
	public int Pressure { get; set; }
	
	[Column("WIND_SPEED")]
	public decimal WindSpeed { get; set; }
	
	[Column("WIND_DIRECTION")]
	[StringLength(50)]
	public string WindDirection { get; set; }
	
	[Column("CONDITION", TypeName = "nvarchar(50)")]
	public WeatherCondition Condition { get; set; }
	
	[Column("VISIBILITY")]
	public int Visibility { get; set; }
	
	[Column("UV_INDEX")]
	public short UvIndex { get; set; }
	
	[Column("PRECIPITATION")]
	public decimal Precipitation { get; set; }
	
	[Column("CLOUD_COVERAGE")]
	public short CloudCoverage { get; set; }
	
	[Column("LAST_UPDATED")]
	public DateTime LastUpdated { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[ForeignKey("CityId")]
	[InverseProperty(nameof(City.WeatherDataItems))]
	public virtual City City { get; set; } = null!;
}

