// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.WeatherModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Domain.Entities;

[Table("WEATHER_ALERTS")]
public partial class WeatherAlert : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("CITY_ID")]
	public int CityId { get; set; }
	
	[Column("ALERT_TYPE")]
	[StringLength(50)]
	public string AlertType { get; set; }
	
	[Column("SEVERITY", TypeName = "nvarchar(50)")]
	public AlertSeverity Severity { get; set; }
	
	[Column("DESCRIPTION")]
	[StringLength(1000)]
	public string Description { get; set; }
	
	[Column("START_TIME")]
	public DateTime StartTime { get; set; }
	
	[Column("END_TIME")]
	public DateTime EndTime { get; set; }
	
	[Column("IS_ACTIVE")]
	public bool IsActive { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[ForeignKey("CityId")]
	[InverseProperty(nameof(City.WeatherAlerts))]
	public virtual City City { get; set; } = null!;
}

