// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentModerationQueue;
using QuickCode.BirHaber.CommentModule.Application.Mappings;
using QuickCode.BirHaber.CommentModule.Persistence.Sql;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Persistence.Repositories
{
    public partial class CommentModerationQueueRepository : BaseRepository, ICommentModerationQueueRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CommentModerationQueueRepository(ILogger<CommentModerationQueueRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CommentModerationQueue")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CommentModerationQueueDto>> InsertAsync(CommentModerationQueueDto value)
        {
            return await ExecuteWithExceptionHandling(CommentModerationQueueCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentModerationQueue.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CommentModerationQueueCrudSqlBindings.ParameterNamePrefix, value, CommentModerationQueueCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CommentModerationQueue>(sql, p);
                return new RepoResponse<CommentModerationQueueDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CommentModerationQueueDto value)
        {
            return await ExecuteWithExceptionHandling(CommentModerationQueueCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentModerationQueue.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CommentModerationQueueCrudSqlBindings.ParameterNamePrefix, value, CommentModerationQueueCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CommentModerationQueueDto value)
        {
            return await ExecuteWithExceptionHandling(CommentModerationQueueCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentModerationQueue.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CommentModerationQueueCrudSqlBindings.ParameterNamePrefix, value, CommentModerationQueueCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CommentModerationQueueDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CommentModerationQueueCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentModerationQueue.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CommentModerationQueueCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CommentModerationQueue>(sql, p);
                return row == null ? CreateNotFoundResponse<CommentModerationQueueDto>("Not found in CommentModerationQueue") : new RepoResponse<CommentModerationQueueDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CommentModerationQueueDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CommentModerationQueueCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CommentModerationQueueDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CommentModerationQueue.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CommentModerationQueue>(sql, p);
                return new RepoResponse<List<CommentModerationQueueDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CommentModerationQueueCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentModerationQueue.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}