-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 WD.[ID], WD.[TEMPERATURE], WD.[FEELS_LIKE], WD.[HUMIDITY], WD.[PRESSURE], WD.[WIND_SPEED], WD.[CONDITION], WD.[LAST_UPDATED] 
FROM [WEATHER_DATAS] WD 
WHERE WD.[IsDeleted] = 0 
	AND WD.[CITY_ID] = @PRM_WEATHER_DATA_CITY_ID 
ORDER BY WD.[LAST_UPDATED] DESC 