-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS QUEUE_SIZE 
FROM [COMMENT_MODERATION_QUEUES] CMQ 
WHERE CMQ.[IsDeleted] = 0 
	AND CMQ.[STATUS] = 'PENDING' 