-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CMQ.[ID], CMQ.[COMMENT_ID], CMQ.[ASSIGNED_MODERATOR_ID], CMQ.[PRIORITY], CMQ.[CREATED_DATE] 
FROM [COMMENT_MODERATION_QUEUES] CMQ 
WHERE CMQ.[IsDeleted] = 0 
	AND CMQ.[STATUS] = 'PENDING' 
ORDER BY CMQ.[PRIORITY] DESC,
	CMQ.[CREATED_DATE] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 