// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.CategoryModule.Application.Dtos.CategoryModerator;

namespace QuickCode.BirHaber.CategoryModule.Persistence.Repositories;
internal static class CategoryModeratorCrudSqlBindings
{
    public const string StoreTableName = "CATEGORY_MODERATORS";
    public const string ParameterNamePrefix = "CATEGORY_MODERATOR";
    public const string IdParameterName = "PRM_CATEGORY_MODERATOR_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetByCategory = "GetByCategory";
        public const string GetByModerator = "GetByModerator";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string RemoveModerator = "RemoveModerator";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CATEGORY_ID", nameof(CategoryModeratorDto.CategoryId)),
        ("MODERATOR_ID", nameof(CategoryModeratorDto.ModeratorId)),
        ("ASSIGNED_DATE", nameof(CategoryModeratorDto.AssignedDate)),
        ("IS_ACTIVE", nameof(CategoryModeratorDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CATEGORY_ID", nameof(CategoryModeratorDto.CategoryId)),
        ("MODERATOR_ID", nameof(CategoryModeratorDto.ModeratorId)),
        ("ASSIGNED_DATE", nameof(CategoryModeratorDto.AssignedDate)),
        ("IS_ACTIVE", nameof(CategoryModeratorDto.IsActive)),
        ("ID", nameof(CategoryModeratorDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CategoryModeratorDto.Id))
    };
}