IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_QUEUES', N'U') AND name = N'IX_NOTIFICATION_QUEUES_IsDeleted')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_QUEUES_IsDeleted] ON [dbo].[NOTIFICATION_QUEUES] ([IsDeleted]);
END