IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') AND name = N'IX_NOTIFICATIONS_CHANNEL_STATUS')
BEGIN
    CREATE INDEX [IX_NOTIFICATIONS_CHANNEL_STATUS] ON [dbo].[NOTIFICATIONS] ([CHANNEL], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') AND name = N'IX_NOTIFICATIONS_READER_ID_NOTIFICATION_TYPE')
BEGIN
    CREATE INDEX [IX_NOTIFICATIONS_READER_ID_NOTIFICATION_TYPE] ON [dbo].[NOTIFICATIONS] ([READER_ID], [NOTIFICATION_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') AND name = N'IX_NOTIFICATIONS_RELATED_ARTICLE_ID')
BEGIN
    CREATE INDEX [IX_NOTIFICATIONS_RELATED_ARTICLE_ID] ON [dbo].[NOTIFICATIONS] ([RELATED_ARTICLE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') AND name = N'IX_NOTIFICATIONS_STATUS_READ_DATE')
BEGIN
    CREATE INDEX [IX_NOTIFICATIONS_STATUS_READ_DATE] ON [dbo].[NOTIFICATIONS] ([STATUS], [READ_DATE]);
END