IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_PREFERENCES', N'U') AND name = N'IX_NOTIFICATION_PREFERENCES_READER_ID_IS_ENABLED')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_PREFERENCES_READER_ID_IS_ENABLED] ON [dbo].[NOTIFICATION_PREFERENCES] ([READER_ID], [IS_ENABLED]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_PREFERENCES', N'U') AND name = N'IX_NOTIFICATION_PREFERENCES_READER_ID_NOTIFICATION_TYPE_CHANNEL')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_PREFERENCES_READER_ID_NOTIFICATION_TYPE_CHANNEL] ON [dbo].[NOTIFICATION_PREFERENCES] ([READER_ID], [NOTIFICATION_TYPE], [CHANNEL]);
END