IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_STATISTICS', N'U') AND name = N'IX_NOTIFICATION_STATISTICS_IsDeleted')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_STATISTICS_IsDeleted] ON [dbo].[NOTIFICATION_STATISTICS] ([IsDeleted]);
END