IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_TEMPLATES', N'U') AND name = N'IX_NOTIFICATION_TEMPLATES_IsDeleted')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_TEMPLATES_IsDeleted] ON [dbo].[NOTIFICATION_TEMPLATES] ([IsDeleted]);
END