IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_STATISTICS', N'U') AND name = N'IX_NOTIFICATION_STATISTICS_NOTIFICATION_TYPE')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_STATISTICS_NOTIFICATION_TYPE] ON [dbo].[NOTIFICATION_STATISTICS] ([NOTIFICATION_TYPE]);
END