IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_BATCHES', N'U') AND name = N'IX_NOTIFICATION_BATCHES_IsDeleted')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_BATCHES_IsDeleted] ON [dbo].[NOTIFICATION_BATCHES] ([IsDeleted]);
END