IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_NOTIFICATION_QUEUES_NOTIFICATIONS_NOTIFICATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.NOTIFICATION_QUEUES'))
BEGIN
    ALTER TABLE [dbo].[NOTIFICATION_QUEUES] ADD CONSTRAINT [FK_NOTIFICATION_QUEUES_NOTIFICATIONS_NOTIFICATION_ID] FOREIGN KEY ([NOTIFICATION_ID]) REFERENCES [dbo].[NOTIFICATIONS] ([ID]);
END