IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_BATCHES', N'U') AND name = N'IX_NOTIFICATION_BATCHES_NOTIFICATION_TYPE')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_BATCHES_NOTIFICATION_TYPE] ON [dbo].[NOTIFICATION_BATCHES] ([NOTIFICATION_TYPE]);
END