IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATIONS', N'U') AND name = N'IX_NOTIFICATIONS_IsDeleted')
BEGIN
    CREATE INDEX [IX_NOTIFICATIONS_IsDeleted] ON [dbo].[NOTIFICATIONS] ([IsDeleted]);
END