IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_NOTIFICATIONS_ARTICLES_RELATED_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.NOTIFICATIONS'))
BEGIN
    ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK_NOTIFICATIONS_ARTICLES_RELATED_ARTICLE_ID] FOREIGN KEY ([RELATED_ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END