IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_PREFERENCES', N'U') AND name = N'IX_NOTIFICATION_PREFERENCES_IsDeleted')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_PREFERENCES_IsDeleted] ON [dbo].[NOTIFICATION_PREFERENCES] ([IsDeleted]);
END