IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_QUEUES', N'U') AND name = N'IX_NOTIFICATION_QUEUES_CHANNEL_STATUS')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_QUEUES_CHANNEL_STATUS] ON [dbo].[NOTIFICATION_QUEUES] ([CHANNEL], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_QUEUES', N'U') AND name = N'IX_NOTIFICATION_QUEUES_NOTIFICATION_ID')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_QUEUES_NOTIFICATION_ID] ON [dbo].[NOTIFICATION_QUEUES] ([NOTIFICATION_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_QUEUES', N'U') AND name = N'IX_NOTIFICATION_QUEUES_STATUS_CREATED_DATE')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_QUEUES_STATUS_CREATED_DATE] ON [dbo].[NOTIFICATION_QUEUES] ([STATUS], [CREATED_DATE]);
END