IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_TEMPLATES', N'U') AND name = N'IX_NOTIFICATION_TEMPLATES_CHANNEL_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_TEMPLATES_CHANNEL_IS_ACTIVE] ON [dbo].[NOTIFICATION_TEMPLATES] ([CHANNEL], [IS_ACTIVE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.NOTIFICATION_TEMPLATES', N'U') AND name = N'IX_NOTIFICATION_TEMPLATES_NOTIFICATION_TYPE_CHANNEL')
BEGIN
    CREATE INDEX [IX_NOTIFICATION_TEMPLATES_NOTIFICATION_TYPE_CHANNEL] ON [dbo].[NOTIFICATION_TEMPLATES] ([NOTIFICATION_TYPE], [CHANNEL]);
END