IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_NOTIFICATIONS_ARTICLES_RELATED_ARTICLE_ID' AND parent_object_id = OBJECT_ID(N'dbo.NOTIFICATIONS'))
BEGIN
    ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK_NOTIFICATIONS_ARTICLES_RELATED_ARTICLE_ID] FOREIGN KEY ([RELATED_ARTICLE_ID]) REFERENCES [dbo].[ARTICLES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_NOTIFICATION_PREFERENCES_READERS_READER_ID' AND parent_object_id = OBJECT_ID(N'dbo.NOTIFICATION_PREFERENCES'))
BEGIN
    ALTER TABLE [dbo].[NOTIFICATION_PREFERENCES] ADD CONSTRAINT [FK_NOTIFICATION_PREFERENCES_READERS_READER_ID] FOREIGN KEY ([READER_ID]) REFERENCES [dbo].[READERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_NOTIFICATION_QUEUES_NOTIFICATIONS_NOTIFICATION_ID' AND parent_object_id = OBJECT_ID(N'dbo.NOTIFICATION_QUEUES'))
BEGIN
    ALTER TABLE [dbo].[NOTIFICATION_QUEUES] ADD CONSTRAINT [FK_NOTIFICATION_QUEUES_NOTIFICATIONS_NOTIFICATION_ID] FOREIGN KEY ([NOTIFICATION_ID]) REFERENCES [dbo].[NOTIFICATIONS] ([ID]);
END