IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_NOTIFICATION_PREFERENCES_READERS_READER_ID' AND parent_object_id = OBJECT_ID(N'dbo.NOTIFICATION_PREFERENCES'))
BEGIN
    ALTER TABLE [dbo].[NOTIFICATION_PREFERENCES] ADD CONSTRAINT [FK_NOTIFICATION_PREFERENCES_READERS_READER_ID] FOREIGN KEY ([READER_ID]) REFERENCES [dbo].[READERS] ([ID]);
END