// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherPreference;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Services.WeatherPreference
{
    public partial interface IWeatherPreferenceService
    {
        Task<Response<WeatherPreferenceDto>> InsertAsync(WeatherPreferenceDto request);
        Task<Response<bool>> DeleteAsync(WeatherPreferenceDto request);
        Task<Response<bool>> UpdateAsync(int id, WeatherPreferenceDto request);
        Task<Response<List<WeatherPreferenceDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<WeatherPreferenceDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByReaderResponseDto>>> GetByReaderAsync(int weatherPreferenceReaderId, int? pageNumber, int? pageSize);
        Task<Response<List<GetAlertEnabledResponseDto>>> GetAlertEnabledAsync(int weatherPreferenceReaderId, int? pageNumber, int? pageSize);
        Task<Response<int>> ToggleAlertsAsync(int weatherPreferenceId, ToggleAlertsRequestDto updateRequest);
        Task<Response<int>> ToggleNotificationsAsync(int weatherPreferenceId, ToggleNotificationsRequestDto updateRequest);
        Task<Response<int>> RemovePreferenceAsync(int weatherPreferenceReaderId, int weatherPreferenceCityId);
    }
}