// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.CommentModule.Domain.Entities;
using QuickCode.BirHaber.CommentModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.CommentModule.Application.Dtos.CommentReport;
using QuickCode.BirHaber.CommentModule.Application.Mappings;
using QuickCode.BirHaber.CommentModule.Persistence.Sql;
using QuickCode.BirHaber.CommentModule.Domain.Enums;

namespace QuickCode.BirHaber.CommentModule.Persistence.Repositories
{
    public partial class CommentReportRepository : BaseRepository, ICommentReportRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CommentReportRepository(ILogger<CommentReportRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CommentReport")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CommentReportDto>> InsertAsync(CommentReportDto value)
        {
            return await ExecuteWithExceptionHandling(CommentReportCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentReport.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CommentReportCrudSqlBindings.ParameterNamePrefix, value, CommentReportCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CommentReport>(sql, p);
                return new RepoResponse<CommentReportDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CommentReportDto value)
        {
            return await ExecuteWithExceptionHandling(CommentReportCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentReport.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CommentReportCrudSqlBindings.ParameterNamePrefix, value, CommentReportCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CommentReportDto value)
        {
            return await ExecuteWithExceptionHandling(CommentReportCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentReport.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CommentReportCrudSqlBindings.ParameterNamePrefix, value, CommentReportCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CommentReportDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CommentReportCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentReport.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CommentReportCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CommentReport>(sql, p);
                return row == null ? CreateNotFoundResponse<CommentReportDto>("Not found in CommentReport") : new RepoResponse<CommentReportDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CommentReportDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CommentReportCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CommentReportDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CommentReport.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CommentReport>(sql, p);
                return new RepoResponse<List<CommentReportDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CommentReportCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommentReport.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}