// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.Reader;
using ReaderEntity = QuickCode.BirHaber.NotificationModule.Domain.Entities.Reader;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Mappings
{
    public static class ReaderMappings
    {
        public static List<ReaderDto> ToDto(this IEnumerable<ReaderEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ReaderDto ToDto(this ReaderEntity model)
        {
            return new ReaderDto
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static ReaderEntity ToEntity(this ReaderDto model)
        {
            return new ReaderEntity
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}