// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.ContentModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;

namespace QuickCode.BirHaber.ContentModule.Domain.Entities;

[Table("CONTENT_CATEGORIES")]
public partial class ContentCategory : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("ARTICLE_ID")]
	public int ArticleId { get; set; }
	
	[Column("CATEGORY_ID")]
	public int CategoryId { get; set; }
	
	[Column("ASSIGNED_DATE")]
	public DateTime AssignedDate { get; set; }
	
	[ForeignKey("ArticleId")]
	[InverseProperty(nameof(Article.ContentCategories))]
	public virtual Article Article { get; set; } = null!;
}

