// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.ContentModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;

namespace QuickCode.BirHaber.ContentModule.Domain.Entities;

[Table("FEATURED_ARTICLES")]
public partial class FeaturedArticle : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("ARTICLE_ID")]
	public int ArticleId { get; set; }
	
	[Column("FEATURED_POSITION")]
	public int FeaturedPosition { get; set; }
	
	[Column("START_DATE")]
	public DateTime StartDate { get; set; }
	
	[Column("END_DATE")]
	public DateTime EndDate { get; set; }
	
	[Column("IS_ACTIVE")]
	public bool IsActive { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[ForeignKey("ArticleId")]
	[InverseProperty(nameof(Article.FeaturedArticles))]
	public virtual Article Article { get; set; } = null!;
}

