-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS TOTAL_CATEGORIES,
	SUM(C.[ARTICLE_COUNT]) AS TOTAL_ARTICLES 
FROM [CATEGORIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[IS_ACTIVE] = 1 