-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 C.[ID], C.[NAME], C.[DESCRIPTION], C.[ICON_URL], C.[ARTICLE_COUNT] 
FROM [CATEGORIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[SLUG] = @PRM_CATEGORY_SLUG 
ORDER BY C.[ID] 