-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT C.[ID], C.[NAME], C.[SLUG], C.[DESCRIPTION], C.[ICON_URL], C.[DISPLAY_ORDER], C.[ARTICLE_COUNT] 
FROM [CATEGORIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[STATUS] = 'ACTIVE' 
	AND C.[IS_ACTIVE] = 1 
ORDER BY C.[DISPLAY_ORDER] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 