// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.CategoryModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Category
    {
        public static class Query
        {
            private const string _prefix = "CategoryModule.Category.Query";
            private const string _sqlScriptStem = "Category";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string GetParentCategories => ResourceKey($"{_sqlScriptStem}.GetParentCategories.g.sql");
            public static string GetSubcategories => ResourceKey($"{_sqlScriptStem}.GetSubcategories.g.sql");
            public static string GetBySlug => ResourceKey($"{_sqlScriptStem}.GetBySlug.g.sql");
            public static string SearchByName => ResourceKey($"{_sqlScriptStem}.SearchByName.g.sql");
            public static string GetTopCategories => ResourceKey($"{_sqlScriptStem}.GetTopCategories.g.sql");
            public static string GetCategoryStats => ResourceKey($"{_sqlScriptStem}.GetCategoryStats.g.sql");
        }
    }
}