-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[WEATHER_PREFERENCES]
SET
    [READER_ID] = @PRM_WEATHER_PREFERENCE_READER_ID,
    [CITY_ID] = @PRM_WEATHER_PREFERENCE_CITY_ID,
    [ALERT_ENABLED] = @PRM_WEATHER_PREFERENCE_ALERT_ENABLED,
    [NOTIFICATION_ENABLED] = @PRM_WEATHER_PREFERENCE_NOTIFICATION_ENABLED,
    [CREATED_DATE] = @PRM_WEATHER_PREFERENCE_CREATED_DATE
WHERE
    [ID] = @PRM_WEATHER_PREFERENCE_ID
    AND [IsDeleted] = 0;