// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationBatch;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Services.NotificationBatch
{
    public partial class NotificationBatchService : INotificationBatchService
    {
        private readonly ILogger<NotificationBatchService> _logger;
        private readonly INotificationBatchRepository _repository;
        public NotificationBatchService(ILogger<NotificationBatchService> logger, INotificationBatchRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<NotificationBatchDto>> InsertAsync(NotificationBatchDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(NotificationBatchDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, NotificationBatchDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<NotificationBatchDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<NotificationBatchDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetPendingBatchesResponseDto>>> GetPendingBatchesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetPendingBatchesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetByTypeResponseDto>>> GetByTypeAsync(NotificationType notificationBatchNotificationType, int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetByTypeAsync(notificationBatchNotificationType, pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<GetBatchProgressResponseDto>> GetBatchProgressAsync(int notificationBatchId)
        {
            var returnValue = await _repository.GetBatchProgressAsync(notificationBatchId);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetCompletedBatchesResponseDto>>> GetCompletedBatchesAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetCompletedBatchesAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateSentCountAsync(int notificationBatchId, UpdateSentCountRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateSentCountAsync(notificationBatchId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> UpdateDeliveredCountAsync(int notificationBatchId, UpdateDeliveredCountRequestDto updateRequest)
        {
            var returnValue = await _repository.UpdateDeliveredCountAsync(notificationBatchId, updateRequest);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> CompleteBatchAsync(int notificationBatchId, CompleteBatchRequestDto updateRequest)
        {
            var returnValue = await _repository.CompleteBatchAsync(notificationBatchId, updateRequest);
            return returnValue.ToResponse();
        }
    }
}