// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagStatistic;
using QuickCode.BirHaber.TagModule.Application.Mappings;
using QuickCode.BirHaber.TagModule.Persistence.Sql;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories
{
    public partial class TagStatisticRepository : BaseRepository, ITagStatisticRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public TagStatisticRepository(ILogger<TagStatisticRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "TagStatistic")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<TagStatisticDto>> InsertAsync(TagStatisticDto value)
        {
            return await ExecuteWithExceptionHandling(TagStatisticCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagStatistic.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(TagStatisticCrudSqlBindings.ParameterNamePrefix, value, TagStatisticCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.TagStatistic>(sql, p);
                return new RepoResponse<TagStatisticDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(TagStatisticDto value)
        {
            return await ExecuteWithExceptionHandling(TagStatisticCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagStatistic.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(TagStatisticCrudSqlBindings.ParameterNamePrefix, value, TagStatisticCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(TagStatisticDto value)
        {
            return await ExecuteWithExceptionHandling(TagStatisticCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagStatistic.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(TagStatisticCrudSqlBindings.ParameterNamePrefix, value, TagStatisticCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<TagStatisticDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(TagStatisticCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagStatistic.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(TagStatisticCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.TagStatistic>(sql, p);
                return row == null ? CreateNotFoundResponse<TagStatisticDto>("Not found in TagStatistic") : new RepoResponse<TagStatisticDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<TagStatisticDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(TagStatisticCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<TagStatisticDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.TagStatistic.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.TagStatistic>(sql, p);
                return new RepoResponse<List<TagStatisticDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(TagStatisticCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TagStatistic.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}