// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.TagModule.Application.Dtos.TagStatistic;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories;
internal static class TagStatisticCrudSqlBindings
{
    public const string StoreTableName = "TAG_STATISTICS";
    public const string ParameterNamePrefix = "TAG_STATISTIC";
    public const string IdParameterName = "PRM_TAG_STATISTIC_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetByTag = "GetByTag";
        public const string GetTrendingTagsBySearches = "GetTrendingTagsBySearches";
        public const string GetWeeklyStats = "GetWeeklyStats";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("TAG_ID", nameof(TagStatisticDto.TagId)),
        ("DAILY_ARTICLES", nameof(TagStatisticDto.DailyArticles)),
        ("DAILY_VIEWS", nameof(TagStatisticDto.DailyViews)),
        ("DAILY_SEARCHES", nameof(TagStatisticDto.DailySearches)),
        ("STATISTICS_DATE", nameof(TagStatisticDto.StatisticsDate)),
        ("TOTAL_SEARCHES", nameof(TagStatisticDto.TotalSearches))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("TAG_ID", nameof(TagStatisticDto.TagId)),
        ("DAILY_ARTICLES", nameof(TagStatisticDto.DailyArticles)),
        ("DAILY_VIEWS", nameof(TagStatisticDto.DailyViews)),
        ("DAILY_SEARCHES", nameof(TagStatisticDto.DailySearches)),
        ("STATISTICS_DATE", nameof(TagStatisticDto.StatisticsDate)),
        ("TOTAL_SEARCHES", nameof(TagStatisticDto.TotalSearches)),
        ("ID", nameof(TagStatisticDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(TagStatisticDto.Id))
    };
}