// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Application.Dtos.WeatherAlert
{
    public record GetActiveAlertsResponseDto
    {
        public int Id { get; init; }
        public int CityId { get; init; }
        public string AlertType { get; init; }
        public AlertSeverity Severity { get; init; }
        public string Description { get; init; }
        public DateTime StartTime { get; init; }
    }
}