-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[COMMENT_LIKES] (
    [COMMENT_ID],
    [READER_ID],
    [LIKE_TYPE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_COMMENT_LIKE_COMMENT_ID,
    @PRM_COMMENT_LIKE_READER_ID,
    @PRM_COMMENT_LIKE_LIKE_TYPE,
    @PRM_COMMENT_LIKE_CREATED_DATE
    );