-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [CITY_ID],
    [TEMPERATURE],
    [FEELS_LIKE],
    [HUMIDITY],
    [PRESSURE],
    [WIND_SPEED],
    [WIND_DIRECTION],
    [CONDITION],
    [VISIBILITY],
    [UV_INDEX],
    [PRECIPITATION],
    [CLOUD_COVERAGE],
    [LAST_UPDATED],
    [CREATED_DATE]
FROM [dbo].[WEATHER_DATAS]
WHERE
    [ID] = @PRM_WEATHER_DATA_ID
    AND [IsDeleted] = 0;