-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[CATEGORY_STATISTICS]
SET
    [CATEGORY_ID] = @PRM_CATEGORY_STATISTIC_CATEGORY_ID,
    [DAILY_ARTICLES] = @PRM_CATEGORY_STATISTIC_DAILY_ARTICLES,
    [DAILY_VIEWS] = @PRM_CATEGORY_STATISTIC_DAILY_VIEWS,
    [STATISTICS_DATE] = @PRM_CATEGORY_STATISTIC_STATISTICS_DATE,
    [DAILY_TOTAL_VIEWS] = @PRM_CATEGORY_STATISTIC_DAILY_TOTAL_VIEWS
WHERE
    [ID] = @PRM_CATEGORY_STATISTIC_ID
    AND [IsDeleted] = 0;