-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [CATEGORY_ID],
    [DAILY_ARTICLES],
    [DAILY_VIEWS],
    [STATISTICS_DATE],
    [DAILY_TOTAL_VIEWS]
FROM [dbo].[CATEGORY_STATISTICS]
WHERE
    [ID] = @PRM_CATEGORY_STATISTIC_ID
    AND [IsDeleted] = 0;