// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.ContentModule.Application.Dtos.ContentRevision;

namespace QuickCode.BirHaber.ContentModule.Persistence.Repositories;
internal static class ContentRevisionCrudSqlBindings
{
    public const string StoreTableName = "CONTENT_REVISIONS";
    public const string ParameterNamePrefix = "CONTENT_REVISION";
    public const string IdParameterName = "PRM_CONTENT_REVISION_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByArticle = "GetByArticle";
        public const string GetByPk = "GetByPk";
        public const string GetRecentRevisions = "GetRecentRevisions";
        public const string GetRevisionCount = "GetRevisionCount";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ARTICLE_ID", nameof(ContentRevisionDto.ArticleId)),
        ("REVISION_NUMBER", nameof(ContentRevisionDto.RevisionNumber)),
        ("TITLE", nameof(ContentRevisionDto.Title)),
        ("CONTENT", nameof(ContentRevisionDto.Content)),
        ("CHANGED_BY_ID", nameof(ContentRevisionDto.ChangedById)),
        ("CHANGE_REASON", nameof(ContentRevisionDto.ChangeReason)),
        ("CREATED_DATE", nameof(ContentRevisionDto.CreatedDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ARTICLE_ID", nameof(ContentRevisionDto.ArticleId)),
        ("REVISION_NUMBER", nameof(ContentRevisionDto.RevisionNumber)),
        ("TITLE", nameof(ContentRevisionDto.Title)),
        ("CONTENT", nameof(ContentRevisionDto.Content)),
        ("CHANGED_BY_ID", nameof(ContentRevisionDto.ChangedById)),
        ("CHANGE_REASON", nameof(ContentRevisionDto.ChangeReason)),
        ("CREATED_DATE", nameof(ContentRevisionDto.CreatedDate)),
        ("ID", nameof(ContentRevisionDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(ContentRevisionDto.Id))
    };
}