// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.ContentModule.Domain.Entities;
using QuickCode.BirHaber.ContentModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.ContentModule.Application.Dtos.ContentCategory;
using QuickCode.BirHaber.ContentModule.Application.Mappings;
using QuickCode.BirHaber.ContentModule.Persistence.Sql;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Persistence.Repositories
{
    public partial class ContentCategoryRepository : BaseRepository, IContentCategoryRepository
    {
        public async Task<RepoResponse<int>> RemoveCategoryAsync(int contentCategoryArticleId, int contentCategoryCategoryId)
        {
            return await ExecuteWithExceptionHandling(ContentCategoryCrudSqlBindings.OperationNames.RemoveCategory, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ContentCategory.Command.RemoveCategory);
                var parameters = new
                {
                    PRM_CONTENT_CATEGORY_ARTICLE_ID = contentCategoryArticleId,
                    PRM_CONTENT_CATEGORY_CATEGORY_ID = contentCategoryCategoryId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}