// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.IdentityModule.Domain.Entities;
using QuickCode.BirHaber.IdentityModule.Application.Dtos.ApiMethodAccessGrant;
using System.Threading.Tasks;
using QuickCode.BirHaber.IdentityModule.Domain.Enums;

namespace QuickCode.BirHaber.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IApiMethodAccessGrantRepository : IBaseRepository<ApiMethodAccessGrantDto>
    {
        Task<RepoResponse<ApiMethodAccessGrantDto>> GetByPkAsync(string permissionGroupName, string apiMethodDefinitionKey);
        Task<RepoResponse<List<GetApiMethodAccessGrantNamesResponseDto>>> GetApiMethodAccessGrantNamesAsync(string apiMethodAccessGrantPermissionGroupName);
        Task<RepoResponse<int>> ClearApiMethodAccessGrantsAsync();
    }
}