// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.CommentModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;

namespace QuickCode.BirHaber.CommentModule.Domain.Entities;

[Table("COMMENT_STATISTICS")]
public partial class CommentStatistic : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("ARTICLE_ID")]
	public int ArticleId { get; set; }
	
	[Column("DAILY_COMMENTS")]
	public int DailyComments { get; set; }
	
	[Column("DAILY_APPROVED")]
	public int DailyApproved { get; set; }
	
	[Column("DAILY_REJECTED")]
	public int DailyRejected { get; set; }
	
	[Column("DAILY_SPAM")]
	public int DailySpam { get; set; }
	
	[Column("STATISTICS_DATE")]
	public DateTime StatisticsDate { get; set; }
	
	[ForeignKey("ArticleId")]
	[InverseProperty(nameof(Article.CommentStatistics))]
	public virtual Article Article { get; set; } = null!;
}

