// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.BirHaber.CommentModule.Domain;
using QuickCode.BirHaber.Domain.Shared.Abstractions;
using QuickCode.BirHaber.Domain.Shared.Entities;

namespace QuickCode.BirHaber.CommentModule.Domain.Entities;

[Table("COMMENT_LIKES")]
public partial class CommentLike : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("COMMENT_ID")]
	public int CommentId { get; set; }
	
	[Column("READER_ID")]
	public int ReaderId { get; set; }
	
	[Column("LIKE_TYPE")]
	[StringLength(50)]
	public string LikeType { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[ForeignKey("CommentId")]
	[InverseProperty(nameof(Comment.CommentLikes))]
	public virtual Comment Comment { get; set; } = null!;
}

