// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationQueue;
using QuickCode.BirHaber.NotificationModule.Application.Mappings;
using QuickCode.BirHaber.NotificationModule.Persistence.Sql;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Persistence.Repositories
{
    public partial class NotificationQueueRepository : BaseRepository, INotificationQueueRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public NotificationQueueRepository(ILogger<NotificationQueueRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "NotificationQueue")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<NotificationQueueDto>> InsertAsync(NotificationQueueDto value)
        {
            return await ExecuteWithExceptionHandling(NotificationQueueCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NotificationQueue.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(NotificationQueueCrudSqlBindings.ParameterNamePrefix, value, NotificationQueueCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.NotificationQueue>(sql, p);
                return new RepoResponse<NotificationQueueDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(NotificationQueueDto value)
        {
            return await ExecuteWithExceptionHandling(NotificationQueueCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NotificationQueue.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(NotificationQueueCrudSqlBindings.ParameterNamePrefix, value, NotificationQueueCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(NotificationQueueDto value)
        {
            return await ExecuteWithExceptionHandling(NotificationQueueCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NotificationQueue.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(NotificationQueueCrudSqlBindings.ParameterNamePrefix, value, NotificationQueueCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<NotificationQueueDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(NotificationQueueCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NotificationQueue.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(NotificationQueueCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.NotificationQueue>(sql, p);
                return row == null ? CreateNotFoundResponse<NotificationQueueDto>("Not found in NotificationQueue") : new RepoResponse<NotificationQueueDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<NotificationQueueDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(NotificationQueueCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<NotificationQueueDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.NotificationQueue.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.NotificationQueue>(sql, p);
                return new RepoResponse<List<NotificationQueueDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(NotificationQueueCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NotificationQueue.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}