// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.CategoryModule.Application.Dtos.FeaturedCategory;

namespace QuickCode.BirHaber.CategoryModule.Persistence.Repositories;
internal static class FeaturedCategoryCrudSqlBindings
{
    public const string StoreTableName = "FEATURED_CATEGORIES";
    public const string ParameterNamePrefix = "FEATURED_CATEGORY";
    public const string IdParameterName = "PRM_FEATURED_CATEGORY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActiveFeatured = "GetActiveFeatured";
        public const string GetByPk = "GetByPk";
        public const string GetExpired = "GetExpired";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("CATEGORY_ID", nameof(FeaturedCategoryDto.CategoryId)),
        ("FEATURED_POSITION", nameof(FeaturedCategoryDto.FeaturedPosition)),
        ("START_DATE", nameof(FeaturedCategoryDto.StartDate)),
        ("END_DATE", nameof(FeaturedCategoryDto.EndDate)),
        ("IS_ACTIVE", nameof(FeaturedCategoryDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("CATEGORY_ID", nameof(FeaturedCategoryDto.CategoryId)),
        ("FEATURED_POSITION", nameof(FeaturedCategoryDto.FeaturedPosition)),
        ("START_DATE", nameof(FeaturedCategoryDto.StartDate)),
        ("END_DATE", nameof(FeaturedCategoryDto.EndDate)),
        ("IS_ACTIVE", nameof(FeaturedCategoryDto.IsActive)),
        ("ID", nameof(FeaturedCategoryDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(FeaturedCategoryDto.Id))
    };
}