// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.ContentModule.Domain.Entities;
using QuickCode.BirHaber.ContentModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.ContentModule.Application.Dtos.FeaturedArticle;
using QuickCode.BirHaber.ContentModule.Application.Mappings;
using QuickCode.BirHaber.ContentModule.Persistence.Sql;
using QuickCode.BirHaber.ContentModule.Domain.Enums;

namespace QuickCode.BirHaber.ContentModule.Persistence.Repositories
{
    public partial class FeaturedArticleRepository : BaseRepository, IFeaturedArticleRepository
    {
        public async Task<RepoResponse<int>> DeactivateAsync(int featuredArticleId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(FeaturedArticleCrudSqlBindings.OperationNames.Deactivate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.FeaturedArticle.Command.Deactivate);
                var parameters = new
                {
                    PRM_FEATURED_ARTICLE_ID = featuredArticleId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}