-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [ARTICLE_ID],
    [READER_ID],
    [PARENT_COMMENT_ID],
    [CONTENT],
    [STATUS],
    [SENTIMENT],
    [LIKE_COUNT],
    [DISLIKE_COUNT],
    [IS_PINNED],
    [APPROVED_DATE],
    [CREATED_DATE],
    [UPDATED_DATE]
FROM [dbo].[COMMENTS]
WHERE
    [ID] = @PRM_COMMENT_ID
    AND [IsDeleted] = 0;