-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[CITIES] (
    [NAME],
    [COUNTRY],
    [LATITUDE],
    [LONGITUDE],
    [TIMEZONE],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_CITY_NAME,
    @PRM_CITY_COUNTRY,
    @PRM_CITY_LATITUDE,
    @PRM_CITY_LONGITUDE,
    @PRM_CITY_TIMEZONE,
    @PRM_CITY_IS_ACTIVE,
    @PRM_CITY_CREATED_DATE
    );