// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.NotificationModule.Domain.Entities;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.Reader;
using QuickCode.BirHaber.NotificationModule.Domain.Enums;

namespace QuickCode.BirHaber.NotificationModule.Application.Services.Reader
{
    public partial class ReaderService : IReaderService
    {
        private readonly ILogger<ReaderService> _logger;
        private readonly IReaderRepository _repository;
        public ReaderService(ILogger<ReaderService> logger, IReaderRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<ReaderDto>> InsertAsync(ReaderDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(ReaderDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, ReaderDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<List<ReaderDto>>> ListAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.ListAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }

        public async Task<Response<ReaderDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize)
        {
            var returnValue = await _repository.GetActiveAsync(pageNumber, pageSize);
            return returnValue.ToResponse();
        }
    }
}