// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.NotificationModule.Application.Services.NotificationStatistic;
using QuickCode.BirHaber.NotificationModule.Application.Dtos.NotificationStatistic;
using QuickCode.BirHaber.NotificationModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.Infrastructure.Web.Helpers;
using QuickCode.BirHaber.Application.Contracts;

namespace QuickCode.BirHaber.NotificationModule.Application.Tests.Services.NotificationStatistic
{
    public class NotificationStatisticServiceDeleteTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<INotificationStatisticRepository> _repositoryMock;
        private readonly Mock<ILogger<NotificationStatisticService>> _loggerMock;
        private readonly NotificationStatisticService _service;
        public NotificationStatisticServiceDeleteTests()
        {
            _repositoryMock = new Mock<INotificationStatisticRepository>();
            _loggerMock = new Mock<ILogger<NotificationStatisticService>>();
            _service = new NotificationStatisticService(_loggerMock.Object, _repositoryMock.Object);
        }

        [Fact]
        public async Task DeleteItemAsync_Should_Return_Success_When_Item_Exists()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<NotificationStatisticDto>("tr");
            var fakeGetResponse = new RepoResponse<NotificationStatisticDto>(fakeDto, "Success");
            var fakeDeleteResponse = new RepoResponse<bool>(true, "Success");
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            _repositoryMock.Setup(r => r.DeleteAsync(It.IsAny<NotificationStatisticDto>())).ReturnsAsync(fakeDeleteResponse);
            // Act
            var result = await _service.DeleteItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.True(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.DeleteAsync(It.IsAny<NotificationStatisticDto>()), Times.Once);
        }

        [Fact]
        public async Task DeleteItemAsync_Should_Return_NotFound_When_Item_Does_Not_Exist()
        {
            var fakeDto = TestDataGenerator.CreateFake<NotificationStatisticDto>("tr");
            // Arrange
            var fakeGetResponse = new RepoResponse<NotificationStatisticDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.Id)).ReturnsAsync(fakeGetResponse);
            // Act
            var result = await _service.DeleteItemAsync(fakeDto.Id);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.False(result.Value);
            _repositoryMock.Verify(r => r.GetByPkAsync(fakeDto.Id), Times.Once);
            _repositoryMock.Verify(r => r.DeleteAsync(It.IsAny<NotificationStatisticDto>()), Times.Never);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}