// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.BirHaber.Infrastructure.Integration.Nswag.Clients.TagModuleApi.Contracts;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using QuickCode.BirHaber.Portal.Helpers;

namespace QuickCode.BirHaber.Portal.Models.TagModule
{
    public class TagData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public string SelectedKey { get; set; }
        public TagDto SelectedItem { get; set; }
        public List<TagDto> List { get; set; }
    }

    public static partial class TagExtensions
    {
        public static string GetKey(this TagDto dto)
        {
            return $"{dto.Id}";
        }
    }
}