-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[CONTENT_REVISIONS]
SET
    [ARTICLE_ID] = @PRM_CONTENT_REVISION_ARTICLE_ID,
    [REVISION_NUMBER] = @PRM_CONTENT_REVISION_REVISION_NUMBER,
    [TITLE] = @PRM_CONTENT_REVISION_TITLE,
    [CONTENT] = @PRM_CONTENT_REVISION_CONTENT,
    [CHANGED_BY_ID] = @PRM_CONTENT_REVISION_CHANGED_BY_ID,
    [CHANGE_REASON] = @PRM_CONTENT_REVISION_CHANGE_REASON,
    [CREATED_DATE] = @PRM_CONTENT_REVISION_CREATED_DATE
WHERE
    [ID] = @PRM_CONTENT_REVISION_ID
    AND [IsDeleted] = 0;