// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.TagModule.Application.Dtos.Article;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Services.Article
{
    public partial interface IArticleService
    {
        Task<Response<ArticleDto>> InsertAsync(ArticleDto request);
        Task<Response<bool>> DeleteAsync(ArticleDto request);
        Task<Response<bool>> UpdateAsync(int id, ArticleDto request);
        Task<Response<List<ArticleDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<ArticleDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber, int? pageSize);
    }
}