// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagStatistic;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Services.TagStatistic
{
    public partial interface ITagStatisticService
    {
        Task<Response<TagStatisticDto>> InsertAsync(TagStatisticDto request);
        Task<Response<bool>> DeleteAsync(TagStatisticDto request);
        Task<Response<bool>> UpdateAsync(int id, TagStatisticDto request);
        Task<Response<List<TagStatisticDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<TagStatisticDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByTagResponseDto>>> GetByTagAsync(int tagStatisticTagId, int? pageNumber, int? pageSize);
        Task<Response<List<GetWeeklyStatsResponseDto>>> GetWeeklyStatsAsync(int tagStatisticTagId, int? pageNumber, int? pageSize);
        Task<Response<GetTrendingTagsBySearchesResponseDto>> GetTrendingTagsBySearchesAsync();
    }
}