// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using QuickCode.BirHaber.TagModule.Application.Dtos.TagSynonym;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Application.Services.TagSynonym
{
    public partial interface ITagSynonymService
    {
        Task<Response<TagSynonymDto>> InsertAsync(TagSynonymDto request);
        Task<Response<bool>> DeleteAsync(TagSynonymDto request);
        Task<Response<bool>> UpdateAsync(int id, TagSynonymDto request);
        Task<Response<List<TagSynonymDto>>> ListAsync(int? pageNumber, int? pageSize);
        Task<Response<TagSynonymDto>> GetItemAsync(int id);
        Task<Response<bool>> DeleteItemAsync(int id);
        Task<Response<int>> TotalItemCountAsync();
        Task<Response<List<GetByPrimaryTagResponseDto>>> GetByPrimaryTagAsync(int tagSynonymPrimaryTagId, int? pageNumber, int? pageSize);
        Task<Response<List<GetSynonymsResponseDto>>> GetSynonymsAsync(int tagSynonymSynonymTagId, int? pageNumber, int? pageSize);
        Task<Response<int>> DeactivateAsync(int tagSynonymId, DeactivateRequestDto updateRequest);
        Task<Response<int>> RemoveSynonymAsync(int tagSynonymPrimaryTagId, int tagSynonymSynonymTagId);
    }
}