-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[CATEGORY_MODERATORS]
SET
    [CATEGORY_ID] = @PRM_CATEGORY_MODERATOR_CATEGORY_ID,
    [MODERATOR_ID] = @PRM_CATEGORY_MODERATOR_MODERATOR_ID,
    [ASSIGNED_DATE] = @PRM_CATEGORY_MODERATOR_ASSIGNED_DATE,
    [IS_ACTIVE] = @PRM_CATEGORY_MODERATOR_IS_ACTIVE
WHERE
    [ID] = @PRM_CATEGORY_MODERATOR_ID
    AND [IsDeleted] = 0;