-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TSH.[ID], TSH.[SEARCH_QUERY], TSH.[SEARCH_COUNT] 
FROM [TAG_SEARCH_HISTORIES] TSH 
WHERE TSH.[IsDeleted] = 0 
	AND TSH.[TAG_ID] = @PRM_TAG_SEARCH_HISTORY_TAG_ID 
ORDER BY TSH.[SEARCH_COUNT] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 