// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.WeatherModule.Domain.Entities;
using QuickCode.BirHaber.WeatherModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.WeatherModule.Application.Dtos.City;
using QuickCode.BirHaber.WeatherModule.Application.Mappings;
using QuickCode.BirHaber.WeatherModule.Persistence.Sql;
using QuickCode.BirHaber.WeatherModule.Domain.Enums;

namespace QuickCode.BirHaber.WeatherModule.Persistence.Repositories
{
    public partial class CityRepository : BaseRepository, ICityRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CityCrudSqlBindings.OperationNames.GetActive, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.City.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in City");
                }
            });
        }

        public async Task<RepoResponse<List<GetByCountryResponseDto>>> GetByCountryAsync(string cityCountry, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CityCrudSqlBindings.OperationNames.GetByCountry, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCountryResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.City.Query.GetByCountry);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CITY_COUNTRY = cityCountry,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByCountryResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in City");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string cityName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CityCrudSqlBindings.OperationNames.SearchByName, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.City.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CITY_NAME = cityName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in City");
                }
            });
        }

        public async Task<RepoResponse<List<GetPopularCitiesResponseDto>>> GetPopularCitiesAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(CityCrudSqlBindings.OperationNames.GetPopularCities, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPopularCitiesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.City.Query.GetPopularCities);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPopularCitiesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in City");
                }
            });
        }
    }
}