-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[FEATURED_CATEGORIES] (
    [CATEGORY_ID],
    [FEATURED_POSITION],
    [START_DATE],
    [END_DATE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_FEATURED_CATEGORY_CATEGORY_ID,
    @PRM_FEATURED_CATEGORY_FEATURED_POSITION,
    @PRM_FEATURED_CATEGORY_START_DATE,
    @PRM_FEATURED_CATEGORY_END_DATE,
    @PRM_FEATURED_CATEGORY_IS_ACTIVE
    );