-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS UNREAD_COUNT 
FROM [NOTIFICATIONS] N 
WHERE N.[IsDeleted] = 0 
	AND N.[READER_ID] = @PRM_NOTIFICATION_READER_ID 
	AND N.[STATUS] != 'READ' 