-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [WEATHER_PREFERENCES] 
WHERE [IsDeleted] = 0 
	AND [READER_ID] = @PRM_WEATHER_PREFERENCE_READER_ID 
	AND [CITY_ID] = @PRM_WEATHER_PREFERENCE_CITY_ID