// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.BirHaber.NotificationModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class NotificationBatch
    {
        public static class Command
        {
            private const string _prefix = "NotificationModule.NotificationBatch.Command";
            private const string _sqlScriptStem = "NotificationBatch";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string UpdateSentCount => ResourceKey($"{_sqlScriptStem}.UpdateSentCount.g.sql");
            public static string UpdateDeliveredCount => ResourceKey($"{_sqlScriptStem}.UpdateDeliveredCount.g.sql");
            public static string CompleteBatch => ResourceKey($"{_sqlScriptStem}.CompleteBatch.g.sql");
        }
    }
}