// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.TagModule.Application.Dtos.ArticleTag;
using QuickCode.BirHaber.TagModule.Application.Mappings;
using QuickCode.BirHaber.TagModule.Persistence.Sql;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories
{
    public partial class ArticleTagRepository : BaseRepository, IArticleTagRepository
    {
        public async Task<RepoResponse<List<GetByArticleResponseDto>>> GetByArticleAsync(int articleTagArticleId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.GetByArticle, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByArticleResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ArticleTag.Query.GetByArticle);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ARTICLE_TAG_ARTICLE_ID = articleTagArticleId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByArticleResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ArticleTag");
                }
            });
        }

        public async Task<RepoResponse<List<GetByTagResponseDto>>> GetByTagAsync(int articleTagTagId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.GetByTag, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByTagResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ArticleTag.Query.GetByTag);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ARTICLE_TAG_TAG_ID = articleTagTagId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByTagResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ArticleTag");
                }
            });
        }

        public async Task<RepoResponse<GetTagCountByArticleResponseDto>> GetTagCountByArticleAsync(int articleTagArticleId)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.GetTagCountByArticle, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Query.GetTagCountByArticle);
                var parameters = new
                {
                    PRM_ARTICLE_TAG_ARTICLE_ID = articleTagArticleId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetTagCountByArticleResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ArticleTag");
            });
        }
    }
}