// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.TagModule.Application.Dtos.ArticleTag;
using QuickCode.BirHaber.TagModule.Application.Mappings;
using QuickCode.BirHaber.TagModule.Persistence.Sql;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories
{
    public partial class ArticleTagRepository : BaseRepository, IArticleTagRepository
    {
        public async Task<RepoResponse<int>> RemoveTagAsync(int articleTagArticleId, int articleTagTagId)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.RemoveTag, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Command.RemoveTag);
                var parameters = new
                {
                    PRM_ARTICLE_TAG_ARTICLE_ID = articleTagArticleId,
                    PRM_ARTICLE_TAG_TAG_ID = articleTagTagId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}