// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.BirHaber.Application.Contracts;
using QcEntity = global::QuickCode.BirHaber.TagModule.Domain.Entities;
using QuickCode.BirHaber.TagModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.BirHaber.Infrastructure.Data;
using QuickCode.BirHaber.Infrastructure.Data.Extensions;
using QuickCode.BirHaber.Infrastructure.Data.Helpers;
using QuickCode.BirHaber.TagModule.Application.Dtos.ArticleTag;
using QuickCode.BirHaber.TagModule.Application.Mappings;
using QuickCode.BirHaber.TagModule.Persistence.Sql;
using QuickCode.BirHaber.TagModule.Domain.Enums;

namespace QuickCode.BirHaber.TagModule.Persistence.Repositories
{
    public partial class ArticleTagRepository : BaseRepository, IArticleTagRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public ArticleTagRepository(ILogger<ArticleTagRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "ArticleTag")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<ArticleTagDto>> InsertAsync(ArticleTagDto value)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(ArticleTagCrudSqlBindings.ParameterNamePrefix, value, ArticleTagCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.ArticleTag>(sql, p);
                return new RepoResponse<ArticleTagDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ArticleTagDto value)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(ArticleTagCrudSqlBindings.ParameterNamePrefix, value, ArticleTagCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ArticleTagDto value)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(ArticleTagCrudSqlBindings.ParameterNamePrefix, value, ArticleTagCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<ArticleTagDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(ArticleTagCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.ArticleTag>(sql, p);
                return row == null ? CreateNotFoundResponse<ArticleTagDto>("Not found in ArticleTag") : new RepoResponse<ArticleTagDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<ArticleTagDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ArticleTagDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.ArticleTag>(sql, p);
                return new RepoResponse<List<ArticleTagDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(ArticleTagCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ArticleTag.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}