-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [ARTICLE_ID],
    [DAILY_VIEWS],
    [DAILY_COMMENTS],
    [DAILY_SHARES],
    [STATISTICS_DATE],
    [TOTAL_VIEWS]
FROM [dbo].[ARTICLE_STATISTICS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;