-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT AT.[ID], AT.[ARTICLE_ID], AT.[ASSIGNED_DATE] 
FROM [ARTICLE_TAGS] AT 
WHERE AT.[IsDeleted] = 0 
	AND AT.[TAG_ID] = @PRM_ARTICLE_TAG_TAG_ID 
ORDER BY AT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 