-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT C.[ID], C.[NAME], C.[LATITUDE], C.[LONGITUDE] 
FROM [CITIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[COUNTRY] = @PRM_CITY_COUNTRY 
	AND C.[IS_ACTIVE] = 1 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 